# Generated by Django 5.2.12 on 2026-04-01 03:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NhanVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_nhan_vien",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã nhân viên"
                    ),
                ),
                ("ho_ten", models.CharField(max_length=255, verbose_name="Họ tên")),
                (
                    "ngay_sinh",
                    models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
                ),
                (
                    "cmnd_ccc",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="CMND/CCCD"
                    ),
                ),
                (
                    "ma_so_thue",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Mã số thuế"
                    ),
                ),
                (
                    "so_dien_thoai",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "so_tai_khoan",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Số tài khoản ngân hàng",
                    ),
                ),
                (
                    "luong_co_ban",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Lương cơ bản",
                    ),
                ),
                (
                    "he_so_phu_cap",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Hệ số phụ cấp",
                    ),
                ),
                (
                    "so_nguoi_phu_thuoc",
                    models.IntegerField(default=0, verbose_name="Số người phụ thuộc"),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("dang_lam_viec", "Đang làm việc"),
                            ("nghi_viec", "Đã nghỉ việc"),
                            ("tam_ngung", "Tạm ngừng"),
                        ],
                        default="dang_lam_viec",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "ngay_vao_lam",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày vào làm"
                    ),
                ),
                (
                    "ngay_nghi",
                    models.DateField(blank=True, null=True, verbose_name="Ngày nghỉ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Nhân viên",
                "verbose_name_plural": "Nhân viên",
                "ordering": ["ma_nhan_vien"],
            },
        ),
        migrations.CreateModel(
            name="BangLuong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thang", models.IntegerField(verbose_name="Tháng")),
                ("nam", models.IntegerField(verbose_name="Năm")),
                (
                    "luong_co_ban",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Lương cơ bản",
                    ),
                ),
                (
                    "phu_cap",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Phụ cấp",
                    ),
                ),
                (
                    "tong_thu_nhap",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Tổng thu nhập",
                    ),
                ),
                (
                    "bhxh_nld",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="BHXH NLĐ (8%)",
                    ),
                ),
                (
                    "bhyt_nld",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="BHYT NLĐ (1.5%)",
                    ),
                ),
                (
                    "bhtn_nld",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="BHTN NLĐ (1%)",
                    ),
                ),
                (
                    "tong_bhxh_nld",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Tổng BHXH NLĐ",
                    ),
                ),
                (
                    "thu_nhap_tinh_thue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Thu nhập tính thuế",
                    ),
                ),
                (
                    "thue_tncn",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Thuế TNCN",
                    ),
                ),
                (
                    "thuc_linh",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Thực lĩnh",
                    ),
                ),
                (
                    "bhxh_dn",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="BHXH DN (17.5%)",
                    ),
                ),
                (
                    "bhyt_dn",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="BHYT DN (3%)",
                    ),
                ),
                (
                    "bhtn_dn",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="BHTN DN (1%)",
                    ),
                ),
                (
                    "bhtnld_bnn_dn",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="BHTNLĐ-BNN DN (0.5%)",
                    ),
                ),
                (
                    "tong_bhxh_dn",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Tổng BHXH DN",
                    ),
                ),
                (
                    "da_hach_toan",
                    models.BooleanField(default=False, verbose_name="Đã hạch toán"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "nhan_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bang_luong",
                        to="luong.nhanvien",
                        verbose_name="Nhân viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bảng lương",
                "verbose_name_plural": "Bảng lương",
                "ordering": ["nam", "thang", "nhan_vien__ma_nhan_vien"],
                "unique_together": {("nhan_vien", "thang", "nam")},
            },
        ),
    ]
