# Generated by Django 6.0.3 on 2026-04-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('danh_muc', '0004_alter_taikhoanketoan_loai_tai_khoan'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiayBaoCo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_chung_tu', models.CharField(max_length=50, unique=True, verbose_name='Số chứng từ')),
                ('ngay', models.DateField(verbose_name='Ngày')),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số tiền')),
                ('dien_giai', models.TextField(blank=True, default='', verbose_name='Diễn giải')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('posted', 'Đã ghi sổ'), ('cancelled', 'Đã hủy')], default='draft', max_length=10, verbose_name='Trạng thái')),
                ('da_doi_chieu', models.BooleanField(default=False, verbose_name='Đã đối chiếu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Người tạo')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Người cập nhật')),
                ('tai_khoan_ngan_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giay_bao_co', to='danh_muc.taikhoannganhang', verbose_name='Tài khoản ngân hàng')),
            ],
            options={
                'verbose_name': 'Giấy báo Có',
                'verbose_name_plural': 'Giấy báo Có',
                'ordering': ['-ngay'],
            },
        ),
        migrations.CreateModel(
            name='GiayBaoNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_chung_tu', models.CharField(max_length=50, unique=True, verbose_name='Số chứng từ')),
                ('ngay', models.DateField(verbose_name='Ngày')),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số tiền')),
                ('dien_giai', models.TextField(blank=True, default='', verbose_name='Diễn giải')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('posted', 'Đã ghi sổ'), ('cancelled', 'Đã hủy')], default='draft', max_length=10, verbose_name='Trạng thái')),
                ('da_doi_chieu', models.BooleanField(default=False, verbose_name='Đã đối chiếu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Người tạo')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Người cập nhật')),
                ('tai_khoan_ngan_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giay_bao_no', to='danh_muc.taikhoannganhang', verbose_name='Tài khoản ngân hàng')),
            ],
            options={
                'verbose_name': 'Giấy báo Nợ',
                'verbose_name_plural': 'Giấy báo Nợ',
                'ordering': ['-ngay'],
            },
        ),
        migrations.CreateModel(
            name='UyNhiemChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_chung_tu', models.CharField(max_length=50, unique=True, verbose_name='Số chứng từ')),
                ('ngay', models.DateField(verbose_name='Ngày')),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số tiền')),
                ('noi_dung', models.TextField(blank=True, default='', verbose_name='Nội dung thanh toán')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=12, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Người tạo')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Người cập nhật')),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uy_nhiem_chi', to='danh_muc.nhacungcap', verbose_name='Nhà cung cấp')),
                ('tai_khoan_ngan_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uy_nhiem_chi', to='danh_muc.taikhoannganhang', verbose_name='Tài khoản ngân hàng')),
            ],
            options={
                'verbose_name': 'Ủy nhiệm chi',
                'verbose_name_plural': 'Ủy nhiệm chi',
                'ordering': ['-ngay'],
            },
        ),
        migrations.CreateModel(
            name='DoiChieuNganHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.IntegerField(verbose_name='Tháng')),
                ('nam', models.IntegerField(verbose_name='Năm')),
                ('so_du_so_sach', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số dư sổ sách')),
                ('so_du_ngan_hang', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số dư ngân hàng')),
                ('chenh_lech', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Chênh lệch')),
                ('trang_thai', models.CharField(choices=[('cho_doi_chieu', 'Chờ đối chiếu'), ('da_doi_chieu', 'Đã đối chiếu'), ('co_chenh_lech', 'Có chênh lệch')], default='cho_doi_chieu', max_length=15, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Người tạo')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Người cập nhật')),
                ('tai_khoan_ngan_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doi_chieu', to='danh_muc.taikhoannganhang', verbose_name='Tài khoản ngân hàng')),
            ],
            options={
                'verbose_name': 'Đối chiếu ngân hàng',
                'verbose_name_plural': 'Đối chiếu ngân hàng',
                'ordering': ['-nam', '-thang'],
                'unique_together': {('tai_khoan_ngan_hang', 'thang', 'nam')},
            },
        ),
    ]
