# Generated by Django 6.0.3 on 2026-04-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nghiep_vu', '0005_buttoan_ngay_dua_vao_su_dung_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BangKeHoaDonBanRa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.IntegerField(verbose_name='Tháng')),
                ('nam', models.IntegerField(verbose_name='Năm')),
                ('ma_so_thue_kh', models.CharField(blank=True, default='', max_length=20, verbose_name='MST khách hàng')),
                ('tien_chua_thue', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tiền chưa thuế')),
                ('thue_gtgt', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Thuế GTGT')),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tổng tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bang_ke_ban_ra', to='nghiep_vu.hoadon', verbose_name='Hóa đơn')),
            ],
            options={
                'verbose_name': 'Bảng kê hóa đơn bán ra',
                'verbose_name_plural': 'Bảng kê hóa đơn bán ra',
                'ordering': ['-nam', '-thang'],
            },
        ),
        migrations.CreateModel(
            name='BangKeHoaDonMuaVao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.IntegerField(verbose_name='Tháng')),
                ('nam', models.IntegerField(verbose_name='Năm')),
                ('ma_so_thue_ncc', models.CharField(blank=True, default='', max_length=20, verbose_name='MST nhà cung cấp')),
                ('tien_chua_thue', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tiền chưa thuế')),
                ('thue_gtgt', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Thuế GTGT')),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tổng tiền')),
                ('loai_hang_hoa', models.CharField(blank=True, default='', max_length=50, verbose_name='Loại hàng hóa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('hoa_don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bang_ke_mua_vao', to='nghiep_vu.hoadon', verbose_name='Hóa đơn')),
            ],
            options={
                'verbose_name': 'Bảng kê hóa đơn mua vào',
                'verbose_name_plural': 'Bảng kê hóa đơn mua vào',
                'ordering': ['-nam', '-thang'],
            },
        ),
        migrations.CreateModel(
            name='ToKhaiGTGT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.IntegerField(verbose_name='Tháng')),
                ('nam', models.IntegerField(verbose_name='Năm')),
                ('tong_doanh_so_ban', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tổng doanh số bán')),
                ('thue_gtgt_dau_ra', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Thuế GTGT đầu ra')),
                ('tong_gia_tri_mua_vao', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tổng giá trị mua vào')),
                ('thue_gtgt_dau_vao', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Thuế GTGT đầu vào')),
                ('thue_gtgt_phai_nop', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Thuế GTGT phải nộp')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('da_nop', 'Đã nộp')], default='draft', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tờ khai GTGT',
                'verbose_name_plural': 'Tờ khai GTGT',
                'ordering': ['-nam', '-thang'],
                'unique_together': {('thang', 'nam')},
            },
        ),
        migrations.CreateModel(
            name='ToKhaiTNCN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.IntegerField(verbose_name='Tháng')),
                ('nam', models.IntegerField(verbose_name='Năm')),
                ('tong_thu_nhap', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tổng thu nhập')),
                ('tong_thue_tncn', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tổng thuế TNCN')),
                ('so_nhan_vien', models.IntegerField(default=0, verbose_name='Số nhân viên')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('da_nop', 'Đã nộp')], default='draft', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tờ khai TNCN',
                'verbose_name_plural': 'Tờ khai TNCN',
                'ordering': ['-nam', '-thang'],
                'unique_together': {('thang', 'nam')},
            },
        ),
        migrations.CreateModel(
            name='ToKhaiTNDNTamTinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quy', models.IntegerField(verbose_name='Quý')),
                ('nam', models.IntegerField(verbose_name='Năm')),
                ('doanh_thu', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Doanh thu')),
                ('chi_phi_duoc_tru', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Chi phí được trừ')),
                ('loi_nhuan', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Lợi nhuận')),
                ('thue_phai_nop', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Thuế phải nộp')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('da_nop', 'Đã nộp')], default='draft', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tờ khai TNDN tạm tính',
                'verbose_name_plural': 'Tờ khai TNDN tạm tính',
                'ordering': ['-nam', '-quy'],
                'unique_together': {('quy', 'nam')},
            },
        ),
    ]
