# Generated by Django 5.2.12 on 2026-03-31 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonVi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_so_thue",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã số thuế"
                    ),
                ),
                (
                    "ten_don_vi",
                    models.CharField(max_length=255, verbose_name="Tên đơn vị"),
                ),
                (
                    "loai_don_vi",
                    models.CharField(
                        choices=[
                            ("tnhh", "Công ty TNHH"),
                            ("cp", "Công ty Cổ phần"),
                            ("dn_tu_nhan", "Doanh nghiệp tư nhân"),
                            ("hop_danh", "Công ty Hợp danh"),
                            ("khac", "Loại khác"),
                        ],
                        max_length=20,
                        verbose_name="Loại đơn vị",
                    ),
                ),
                (
                    "dia_chi",
                    models.TextField(blank=True, default="", verbose_name="Địa chỉ"),
                ),
                (
                    "dien_thoai",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Điện thoại"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "nguoi_dai_dien",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người đại diện",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn vị",
                "verbose_name_plural": "Đơn vị",
            },
        ),
        migrations.CreateModel(
            name="TaiKhoanKeToan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_tai_khoan",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Mã tài khoản"
                    ),
                ),
                (
                    "ten_tai_khoan",
                    models.CharField(max_length=255, verbose_name="Tên tài khoản"),
                ),
                (
                    "cap_do",
                    models.IntegerField(
                        choices=[(1, "Cấp 1"), (2, "Cấp 2")], verbose_name="Cấp độ"
                    ),
                ),
                (
                    "loai_tai_khoan",
                    models.CharField(
                        choices=[
                            ("tai_san", "Tài sản (Assets)"),
                            ("no_phai_tra", "Nợ phải trả (Liabilities)"),
                            ("von_chu_so_huu", "Vốn chủ sở hữu (Owner Equity)"),
                            ("doanh_thu", "Doanh thu (Revenue)"),
                            ("chi_phi", "Chi phí (Expenses)"),
                        ],
                        max_length=20,
                        verbose_name="Loại tài khoản",
                    ),
                ),
                (
                    "mo_ta",
                    models.TextField(blank=True, default="", verbose_name="Mô tả"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                (
                    "is_immutable",
                    models.BooleanField(
                        default=False,
                        help_text="Prevents modification of seeded master data",
                        verbose_name="Bất biến",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
                (
                    "tai_khoan_me",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tai_khoan_con",
                        to="danh_muc.taikhoanketoan",
                        verbose_name="Tài khoản mẹ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tài khoản kế toán",
                "verbose_name_plural": "Tài khoản kế toán",
                "ordering": ["ma_tai_khoan"],
            },
        ),
    ]
