# Generated by Django 5.2.12 on 2026-03-31 09:02

from django.db import migrations


def seed_accounts(apps, schema_editor):
    """Load 71 Tier-1 accounts from Thông tư 99 Appendix II."""
    TaiKhoanKeToan = apps.get_model("danh_muc", "TaiKhoanKeToan")

    accounts = [
        ("111", "Tiền mặt", "tai_san", "Tiền Việt Nam đồng tại quỹ"),
        (
            "112",
            "Tiền gửi ngân hàng",
            "tai_san",
            "Tiền gửi tại các ngân hàng thương mại",
        ),
        (
            "113",
            "Tiền đang chuyển",
            "tai_san",
            "Tiền đang trong quá trình chuyển khoản",
        ),
        ("121", "Chứng khoán kinh doanh", "tai_san", "Chứng khoán kinh doanh ngắn hạn"),
        (
            "128",
            "Đầu tư nắm giữ đến ngày đáo hạn",
            "tai_san",
            "Đầu tư ngắn hạn nắm giữ đến ngày đáo hạn",
        ),
        (
            "131",
            "Phải thu của khách hàng",
            "tai_san",
            "Số tiền phải thu từ khách hàng về hàng hóa, dịch vụ đã giao",
        ),
        (
            "133",
            "Thuế GTGT được khấu trừ",
            "tai_san",
            "Thuế giá trị gia tăng đầu vào được khấu trừ",
        ),
        (
            "136",
            "Phải thu nội bộ",
            "tai_san",
            "Phải thu từ các đơn vị nội bộ, chi nhánh",
        ),
        (
            "138",
            "Phải thu khác",
            "tai_san",
            "Các khoản phải thu không thuộc các tài khoản trên",
        ),
        ("141", "Tạm ứng", "tai_san", "Số tiền đã tạm ứng cho người lao động"),
        ("142", "Chi phí trả trước", "tai_san", "Chi phí trả trước ngắn hạn"),
        (
            "144",
            "Cầm cố, ký cược, ký quỹ ngắn hạn",
            "tai_san",
            "Tiền và tài sản cầm cố, ký cược, ký quỹ ngắn hạn",
        ),
        (
            "151",
            "Hàng mua đang đi trên đường",
            "tai_san",
            "Hàng đã mua, đã trả tiền nhưng chưa về đến kho",
        ),
        ("152", "Nguyên liệu, vật liệu", "tai_san", "Nguyên liệu, vật liệu tồn kho"),
        ("153", "Công cụ, dụng cụ", "tai_san", "Công cụ, dụng cụ tồn kho"),
        (
            "154",
            "Chi phí sản xuất, kinh doanh dở dang",
            "tai_san",
            "Chi phí sản xuất kinh doanh chưa hoàn thành",
        ),
        ("155", "Thành phẩm", "tai_san", "Thành phẩm tồn kho"),
        ("157", "Hàng hóa", "tai_san", "Hàng hóa tồn kho"),
        (
            "158",
            "Hàng hóa kho bảo thuế",
            "tai_san",
            "Hàng hóa lưu trữ tại kho bảo thuế",
        ),
        ("211", "Tài sản cố định hữu hình", "tai_san", "Nguyên giá TSCĐ hữu hình"),
        (
            "212",
            "Tài sản cố định thuê tài chính",
            "tai_san",
            "Nguyên giá TSCĐ thuê tài chính",
        ),
        ("213", "Tài sản cố định vô hình", "tai_san", "Nguyên giá TSCĐ vô hình"),
        ("214", "Hao mòn TSCĐ", "tai_san", "Giá trị hao mòn lũy kế của TSCĐ"),
        ("217", "BĐS đầu tư", "tai_san", "Bất động sản đầu tư"),
        ("221", "Đầu tư vào công ty con", "tai_san", "Vốn đầu tư vào các công ty con"),
        (
            "222",
            "Đầu tư vào công ty liên kết",
            "tai_san",
            "Vốn đầu tư vào các công ty liên kết, liên doanh",
        ),
        (
            "228",
            "Đầu tư góp vốn vào đơn vị khác",
            "tai_san",
            "Vốn góp vào các đơn vị khác",
        ),
        (
            "229",
            "Dự phòng đầu tư tài chính",
            "tai_san",
            "Dự phòng tổn thất đầu tư tài chính",
        ),
        ("241", "XDCB dở dang", "tai_san", "Chi phí xây dựng cơ bản dở dang"),
        ("242", "Chi phí trả trước dài hạn", "tai_san", "Chi phí trả trước dài hạn"),
        (
            "243",
            "Tài sản thuế thu nhập hoãn lại",
            "tai_san",
            "Tài sản thuế TNDN hoãn lại",
        ),
        (
            "244",
            "Ký cược, ký quỹ dài hạn",
            "tai_san",
            "Tiền và tài sản ký cược, ký quỹ dài hạn",
        ),
        ("268", "Tài sản chờ xử lý", "tai_san", "Giá trị tài sản thiếu chờ xử lý"),
        (
            "311",
            "Vay và nợ thuê tài chính ngắn hạn",
            "no_phai_tra",
            "Số tiền vay và nợ thuê tài chính dưới 12 tháng",
        ),
        (
            "315",
            "Nợ thuê tài chính ngắn hạn",
            "no_phai_tra",
            "Nợ thuê tài chính ngắn hạn",
        ),
        (
            "331",
            "Phải trả người bán",
            "no_phai_tra",
            "Số tiền phải trả cho người bán về hàng hóa, dịch vụ",
        ),
        (
            "333",
            "Thuế và các khoản phải nộp Nhà nước",
            "no_phai_tra",
            "Các khoản thuế và phí phải nộp ngân sách nhà nước",
        ),
        (
            "334",
            "Phải trả người lao động",
            "no_phai_tra",
            "Tiền lương, thưởng và các khoản phải trả người lao động",
        ),
        (
            "335",
            "Chi phí phải trả",
            "no_phai_tra",
            "Chi phí đã ghi nhận nhưng chưa thanh toán",
        ),
        (
            "336",
            "Phải trả nội bộ",
            "no_phai_tra",
            "Phải trả cho các đơn vị nội bộ, chi nhánh",
        ),
        (
            "338",
            "Phải trả, phải nộp khác",
            "no_phai_tra",
            "Các khoản phải trả, phải nộp khác",
        ),
        (
            "339",
            "Phải trả cổ đông",
            "no_phai_tra",
            "Cổ tức và lợi nhuận phải trả cho cổ đông",
        ),
        (
            "341",
            "Vay và nợ thuê tài chính dài hạn",
            "no_phai_tra",
            "Số tiền vay và nợ thuê tài chính trên 12 tháng",
        ),
        (
            "343",
            "Trái phiếu phát hành",
            "no_phai_tra",
            "Giá trị trái phiếu đã phát hành",
        ),
        (
            "347",
            "Thuế thu nhập hoãn lại phải trả",
            "no_phai_tra",
            "Thuế TNDN hoãn lại phải trả",
        ),
        (
            "348",
            "Dự phòng trợ cấp mất việc",
            "no_phai_tra",
            "Dự phòng trợ cấp thôi việc, mất việc làm",
        ),
        (
            "351",
            "Quỹ khen thưởng, phúc lợi",
            "no_phai_tra",
            "Quỹ khen thưởng, phúc lợi ngắn hạn",
        ),
        ("352", "Dự phòng phải trả", "no_phai_tra", "Các khoản dự phòng phải trả"),
        (
            "353",
            "Doanh thu chưa thực hiện",
            "no_phai_tra",
            "Doanh thu nhận trước nhưng chưa thực hiện",
        ),
        ("356", "Quỹ ổn định giá", "no_phai_tra", "Quỹ ổn định giá"),
        ("357", "TNDN được giảm trừ", "no_phai_tra", "Thuế TNDN được giảm trừ"),
        ("358", "Vốn đầu tư XDCB", "no_phai_tra", "Vốn đầu tư xây dựng cơ bản"),
        (
            "411",
            "Vốn đầu tư của chủ sở hữu",
            "von_chu_so_huu",
            "Vốn đầu tư từ các chủ sở hữu",
        ),
        (
            "412",
            "Chênh lệch tỷ giá hối đoái",
            "von_chu_so_huu",
            "Chênh lệch tỷ giá hối đoái do đánh giá lại",
        ),
        (
            "413",
            "Chênh lệch đánh giá lại tài sản",
            "von_chu_so_huu",
            "Chênh lệch do đánh giá lại tài sản",
        ),
        (
            "414",
            "Quỹ đầu tư phát triển",
            "von_chu_so_huu",
            "Quỹ đầu tư phát triển doanh nghiệp",
        ),
        (
            "415",
            "Quỹ dự phòng tài chính",
            "von_chu_so_huu",
            "Quỹ dự phòng về tài chính",
        ),
        (
            "418",
            "Các quỹ khác thuộc vốn chủ sở hữu",
            "von_chu_so_huu",
            "Các quỹ khác thuộc nguồn vốn chủ sở hữu",
        ),
        (
            "419",
            "Cổ phiếu quỹ",
            "von_chu_so_huu",
            "Giá trị cổ phiếu do công ty mua lại",
        ),
        (
            "421",
            "Lợi nhuận sau thuế chưa phân phối",
            "von_chu_so_huu",
            "Lợi nhuận sau thuế chưa phân phối cho chủ sở hữu",
        ),
        (
            "431",
            "Quỹ khen thưởng, phúc lợi (dài hạn)",
            "von_chu_so_huu",
            "Quỹ khen thưởng, phúc lợi dài hạn",
        ),
        ("441", "Nguồn kinh phí", "von_chu_so_huu", "Nguồn kinh phí sự nghiệp, dự án"),
        (
            "442",
            "Nguồn kinh phí đã hình thành TSCĐ",
            "von_chu_so_huu",
            "Nguồn kinh phí đã dùng để hình thành TSCĐ",
        ),
        (
            "461",
            "Nguồn vốn đầu tư XDCB",
            "von_chu_so_huu",
            "Nguồn vốn đầu tư xây dựng cơ bản",
        ),
        (
            "511",
            "Doanh thu bán hàng và cung cấp dịch vụ",
            "doanh_thu",
            "Doanh thu từ hoạt động bán hàng và cung cấp dịch vụ",
        ),
        (
            "515",
            "Doanh thu hoạt động tài chính",
            "doanh_thu",
            "Doanh thu từ hoạt động tài chính",
        ),
        ("518", "Doanh thu khác", "doanh_thu", "Doanh thu từ hoạt động khác"),
        (
            "521",
            "Các khoản giảm trừ doanh thu",
            "doanh_thu",
            "Giảm giá, chiết khấu, hàng bán bị trả lại",
        ),
        ("611", "Mua hàng", "chi_phi", "Giá trị hàng mua vào (theo phương pháp KKĐK)"),
        ("631", "Giá vốn hàng bán", "chi_phi", "Giá vốn của hàng hóa, dịch vụ đã bán"),
        ("632", "Doanh thu (kết chuyển)", "chi_phi", "Tài khoản kết chuyển doanh thu"),
        (
            "635",
            "Chi phí tài chính",
            "chi_phi",
            "Chi phí hoạt động tài chính (lãi vay, tỷ giá...)",
        ),
        (
            "641",
            "Chi phí bán hàng",
            "chi_phi",
            "Chi phí phục vụ cho hoạt động bán hàng",
        ),
        (
            "642",
            "Chi phí quản lý doanh nghiệp",
            "chi_phi",
            "Chi phí quản lý hành chính doanh nghiệp",
        ),
        ("651", "Chi phí khác", "chi_phi", "Chi phí từ hoạt động khác"),
        ("711", "Thu nhập khác", "doanh_thu", "Thu nhập từ hoạt động khác"),
        ("811", "Chi phí khác", "chi_phi", "Chi phí từ hoạt động khác"),
        ("821", "Chi phí thuế TNDN", "chi_phi", "Chi phí thuế thu nhập doanh nghiệp"),
        ("881", "Lợi nhuận khác", "chi_phi", "Lợi nhuận khác (kết chuyển)"),
        (
            "911",
            "Xác định kết quả kinh doanh",
            "chi_phi",
            "Tài khoản xác định kết quả hoạt động kinh doanh",
        ),
        ("001", "Nguồn vốn, quỹ", "tai_san", "Tài khoản ngoài bảng - Nguồn vốn và quỹ"),
        (
            "002",
            "Hàng hóa nhận bán, ký gửi",
            "tai_san",
            "Tài khoản ngoài bảng - Hàng nhận bán, ký gửi",
        ),
        ("007", "Ngoại tệ các loại", "tai_san", "Tài khoản ngoài bảng - Ngoại tệ"),
        (
            "008",
            "Chứng từ, giấy tờ có giá",
            "tai_san",
            "Tài khoản ngoài bảng - Chứng từ có giá",
        ),
        (
            "009",
            "Tài sản thuê ngoài",
            "tai_san",
            "Tài khoản ngoài bảng - Tài sản thuê ngoài",
        ),
    ]

    for ma, ten, loai, mo_ta in accounts:
        TaiKhoanKeToan.objects.create(
            ma_tai_khoan=ma,
            ten_tai_khoan=ten,
            cap_do=1,
            loai_tai_khoan=loai,
            mo_ta=mo_ta,
            is_active=True,
            is_immutable=True,
            created_by="system",
            updated_by="system",
        )


def remove_seed_accounts(apps, schema_editor):
    """Remove all seeded accounts."""
    TaiKhoanKeToan = apps.get_model("danh_muc", "TaiKhoanKeToan")
    TaiKhoanKeToan.objects.filter(created_by="system").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("danh_muc", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_accounts, remove_seed_accounts),
    ]
