# Generated by Django 5.1.7 on 2026-03-31 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("danh_muc", "0002_seed_accounts"),
    ]

    operations = [
        migrations.CreateModel(
            name="KhachHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_kh",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã khách hàng"
                    ),
                ),
                (
                    "ten_kh",
                    models.CharField(max_length=255, verbose_name="Tên khách hàng"),
                ),
                (
                    "ma_so_thue",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Mã số thuế"
                    ),
                ),
                (
                    "dia_chi",
                    models.TextField(blank=True, default="", verbose_name="Địa chỉ"),
                ),
                (
                    "dien_thoai",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Điện thoại"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "so_gioi_thieu_dien_tu",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Số giới thiệu điện tử (eTax ID)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
            ],
            options={
                "verbose_name": "Khách hàng",
                "verbose_name_plural": "Khách hàng",
                "ordering": ["ma_kh"],
            },
        ),
        migrations.CreateModel(
            name="NganHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_ngan_hang",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã ngân hàng"
                    ),
                ),
                (
                    "ten_ngan_hang",
                    models.CharField(max_length=255, verbose_name="Tên ngân hàng"),
                ),
                (
                    "ma_dien_toan",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Mã điện toán (SWIFT)",
                    ),
                ),
                (
                    "dia_chi",
                    models.TextField(blank=True, default="", verbose_name="Địa chỉ"),
                ),
            ],
            options={
                "verbose_name": "Ngân hàng",
                "verbose_name_plural": "Ngân hàng",
                "ordering": ["ma_ngan_hang"],
            },
        ),
        migrations.CreateModel(
            name="NhaCungCap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_ncc",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã nhà cung cấp"
                    ),
                ),
                (
                    "ten_ncc",
                    models.CharField(max_length=255, verbose_name="Tên nhà cung cấp"),
                ),
                (
                    "ma_so_thue",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Mã số thuế"
                    ),
                ),
                (
                    "dia_chi",
                    models.TextField(blank=True, default="", verbose_name="Địa chỉ"),
                ),
                (
                    "dien_thoai",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Điện thoại"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "tai_khoan_ngan_hang",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Tài khoản ngân hàng",
                    ),
                ),
                (
                    "ngan_hang",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Ngân hàng"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhà cung cấp",
                "verbose_name_plural": "Nhà cung cấp",
                "ordering": ["ma_ncc"],
            },
        ),
        migrations.CreateModel(
            name="HangHoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_hang_hoa",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã hàng hóa"
                    ),
                ),
                (
                    "ten_hang_hoa",
                    models.CharField(max_length=255, verbose_name="Tên hàng hóa"),
                ),
                (
                    "don_vi_tinh",
                    models.CharField(
                        default="cái", max_length=20, verbose_name="Đơn vị tính"
                    ),
                ),
                (
                    "gia_mua",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Giá mua",
                    ),
                ),
                (
                    "gia_ban",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Giá bán",
                    ),
                ),
                (
                    "thue_suat_gtgt",
                    models.CharField(
                        choices=[("0", "0%"), ("5", "5%"), ("8", "8%"), ("10", "10%")],
                        default="10",
                        max_length=2,
                        verbose_name="Thuế suất GTGT",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
                (
                    "tk_doanh_thu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hang_hoa_doanh_thu",
                        to="danh_muc.taikhoanketoan",
                        verbose_name="TK doanh thu",
                    ),
                ),
                (
                    "tk_gia_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hang_hoa_gia_von",
                        to="danh_muc.taikhoanketoan",
                        verbose_name="TK giá vốn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hàng hóa",
                "verbose_name_plural": "Hàng hóa",
                "ordering": ["ma_hang_hoa"],
            },
        ),
        migrations.CreateModel(
            name="TaiKhoanNganHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_tai_khoan",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Số tài khoản"
                    ),
                ),
                (
                    "ten_chu_tai_khoan",
                    models.CharField(max_length=255, verbose_name="Tên chủ tài khoản"),
                ),
                (
                    "tien_te",
                    models.CharField(
                        default="VND", max_length=10, verbose_name="Tiền tệ"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
                (
                    "ngan_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tai_khoan",
                        to="danh_muc.nganhang",
                        verbose_name="Ngân hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tài khoản ngân hàng",
                "verbose_name_plural": "Tài khoản ngân hàng",
                "ordering": ["so_tai_khoan"],
            },
        ),
    ]
