# Generated by Django 5.0 on 2026-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danh_muc', '0003_khachhang_nganhang_nhacungcap_hanghoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoanketoan',
            name='loai_tai_khoan',
            field=models.CharField(choices=[('tai_san', 'Tài sản (Assets)'), ('no_phai_tra', 'Nợ phải trả (Liabilities)'), ('von_chu_so_huu', 'Vốn chủ sở hữu (Owner Equity)'), ('doanh_thu', 'Doanh thu (Revenue)'), ('chi_phi', 'Chi phí (Expenses)'), ('thu_nhap_khac', 'Thu nhập khác'), ('chi_phi_khac', 'Chi phí khác'), ('xac_dinh_kq', 'Xác định kết quả')], max_length=20, verbose_name='Loại tài khoản'),
        ),
    ]
