# Generated by Django 5.2.12 on 2026-04-02
# Replaces 0002_seed_accounts with full TT 99/2025/TT-BTC Phụ lục II COA

from django.db import migrations


def seed_coa_tt99(apps, schema_editor):
    """
    Seed complete Chart of Accounts per Thông tư 99/2025/TT-BTC Phụ lục II.

    This migration replaces the previous incomplete seed with the full
    ~80 Tier-1 + ~93 Tier-2 accounts.

    Legal basis:
        - Thông tư 99/2025/TT-BTC Phụ lục II - Hệ thống tài khoản kế toán
    """
    TaiKhoanKeToan = apps.get_model("danh_muc", "TaiKhoanKeToan")

    # Delete ALL existing seeded accounts first
    TaiKhoanKeToan.objects.filter(created_by="system").delete()

    tier1_accounts = [
        # LOẠI 1 - TÀI SẢN NGẮN HẠN
        ("111", "Tiền mặt", "tai_san", "Tiền Việt Nam đồng tại quỹ"),
        ("112", "Tiền gửi ngân hàng", "tai_san", "Tiền gửi tại các ngân hàng thương mại"),
        ("113", "Tiền đang chuyển", "tai_san", "Tiền đang trong quá trình chuyển khoản"),
        ("121", "Chứng khoán kinh doanh", "tai_san", "Chứng khoán kinh doanh ngắn hạn"),
        ("122", "Đầu tư nắm giữ đến ngày đáo hạn", "tai_san", "Đầu tư nắm giữ đến ngày đáo hạn ngắn hạn"),
        ("128", "Đầu tư nắm giữ ngắn hạn khác", "tai_san", "Các khoản đầu tư nắm giữ ngắn hạn khác"),
        ("131", "Phải thu của khách hàng", "tai_san", "Số tiền phải thu từ khách hàng về hàng hóa, dịch vụ đã giao"),
        ("133", "Thuế GTGT được khấu trừ", "tai_san", "Thuế giá trị gia tăng đầu vào được khấu trừ"),
        ("136", "Phải thu nội bộ", "tai_san", "Phải thu từ các đơn vị nội bộ, chi nhánh"),
        ("137", "Phải thu theo tiến độ kế hoạch hợp đồng xây dựng", "tai_san", "Phải thu theo tiến độ kế hoạch hợp đồng xây dựng"),
        ("138", "Phải thu khác", "tai_san", "Các khoản phải thu không thuộc các tài khoản trên"),
        ("139", "Dự phòng phải thu khó đòi", "tai_san", "Dự phòng phải thu khó đòi"),
        ("141", "Tạm ứng", "tai_san", "Số tiền đã tạm ứng cho người lao động"),
        ("142", "Chi phí trả trước ngắn hạn", "tai_san", "Chi phí trả trước ngắn hạn"),
        ("144", "Ký cược, ký quỹ ngắn hạn", "tai_san", "Tiền và tài sản ký cược, ký quỹ ngắn hạn"),
        ("151", "Hàng mua đang đi trên đường", "tai_san", "Hàng đã mua, đã trả tiền nhưng chưa về đến kho"),
        ("152", "Nguyên liệu, vật liệu", "tai_san", "Nguyên liệu, vật liệu tồn kho"),
        ("153", "Công cụ, dụng cụ", "tai_san", "Công cụ, dụng cụ tồn kho"),
        ("154", "Chi phí sản xuất, kinh doanh dở dang", "tai_san", "Chi phí sản xuất kinh doanh chưa hoàn thành"),
        ("155", "Sản phẩm", "tai_san", "Sản phẩm tồn kho"),
        ("156", "Hàng hóa", "tai_san", "Hàng hóa tồn kho"),
        ("157", "Hàng gửi đi bán", "tai_san", "Hàng hóa, thành phẩm gửi bán đại lý, ký gửi"),
        ("158", "Nguyên liệu, vật tư tại kho bảo thuế", "tai_san", "Nguyên liệu, vật tư tại kho bảo thuế"),
        ("161", "Thuế và các khoản phải thu Nhà nước", "tai_san", "Thuế và các khoản phải thu từ Nhà nước"),
        ("171", "Giao dịch mua, bán lại trái phiếu chính phủ", "tai_san", "Giao dịch mua, bán lại trái phiếu chính phủ"),
        # LOẠI 2 - TÀI SẢN DÀI HẠN
        ("211", "Tài sản cố định hữu hình", "tai_san", "Nguyên giá TSCĐ hữu hình"),
        ("212", "Tài sản cố định thuê tài chính", "tai_san", "Nguyên giá TSCĐ thuê tài chính"),
        ("213", "Tài sản cố định vô hình", "tai_san", "Nguyên giá TSCĐ vô hình"),
        ("214", "Hao mòn TSCĐ", "tai_san", "Giá trị hao mòn lũy kế của TSCĐ"),
        ("215", "Tài sản sinh học", "tai_san", "Tài sản sinh học"),
        ("217", "Bất động sản đầu tư", "tai_san", "Bất động sản đầu tư"),
        ("221", "Đầu tư vào công ty con", "tai_san", "Vốn đầu tư vào các công ty con"),
        ("222", "Góp vốn liên doanh", "tai_san", "Vốn góp liên doanh, liên kết"),
        ("228", "Đầu tư góp vốn khác", "tai_san", "Vốn góp vào các đơn vị khác"),
        ("229", "Dự phòng đầu tư dài hạn", "tai_san", "Dự phòng tổn thất đầu tư tài chính dài hạn"),
        ("241", "XDCB dở dang", "tai_san", "Chi phí xây dựng cơ bản dở dang"),
        ("242", "Chi phí trả trước dài hạn", "tai_san", "Chi phí trả trước dài hạn"),
        ("243", "Tài sản thuế thu nhập hoãn lại", "tai_san", "Tài sản thuế TNDN hoãn lại"),
        ("244", "Ký cược, ký quỹ dài hạn", "tai_san", "Tiền và tài sản ký cược, ký quỹ dài hạn"),
        ("261", "Ký quỹ, ký cược dài hạn", "tai_san", "Ký quỹ, ký cược dài hạn"),
        # LOẠI 3 - NỢ PHẢI TRẢ
        ("311", "Vay và nợ thuê tài chính ngắn hạn", "no_phai_tra", "Số tiền vay và nợ thuê tài chính dưới 12 tháng"),
        ("312", "Nợ thuê tài chính ngắn hạn", "no_phai_tra", "Nợ thuê tài chính ngắn hạn"),
        ("331", "Phải trả cho người bán", "no_phai_tra", "Số tiền phải trả cho người bán về hàng hóa, dịch vụ"),
        ("333", "Thuế và các khoản phải nộp Nhà nước", "no_phai_tra", "Các khoản thuế và phí phải nộp ngân sách nhà nước"),
        ("334", "Phải trả người lao động", "no_phai_tra", "Tiền lương, thưởng và các khoản phải trả người lao động"),
        ("335", "Chi phí phải trả ngắn hạn", "no_phai_tra", "Chi phí đã ghi nhận nhưng chưa thanh toán"),
        ("336", "Phải trả nội bộ", "no_phai_tra", "Phải trả cho các đơn vị nội bộ, chi nhánh"),
        ("337", "Thanh toán theo tiến độ kế hoạch hợp đồng xây dựng", "no_phai_tra", "Thanh toán theo tiến độ kế hoạch hợp đồng xây dựng"),
        ("338", "Phải trả, phải nộp khác", "no_phai_tra", "Các khoản phải trả, phải nộp khác"),
        ("332", "Phải trả cổ tức, lợi nhuận", "no_phai_tra", "Phải trả cổ tức, lợi nhuận cho chủ sở hữu"),
        ("341", "Vay và nợ thuê tài chính dài hạn", "no_phai_tra", "Số tiền vay và nợ thuê tài chính trên 12 tháng"),
        ("342", "Nợ thuê tài chính dài hạn", "no_phai_tra", "Nợ thuê tài chính dài hạn"),
        ("343", "Trái phiếu phát hành", "no_phai_tra", "Giá trị trái phiếu đã phát hành"),
        ("344", "Nhận ký quỹ, ký cược", "no_phai_tra", "Tiền và tài sản nhận ký quỹ, ký cược"),
        ("347", "Thuế thu nhập hoãn lại phải trả", "no_phai_tra", "Thuế TNDN hoãn lại phải trả"),
        ("349", "Nghĩa vụ khác dài hạn", "no_phai_tra", "Nghĩa vụ khác dài hạn"),
        ("352", "Dự phòng phải trả", "no_phai_tra", "Dự phòng phải trả"),
        ("353", "Quỹ khen thưởng, phúc lợi", "no_phai_tra", "Quỹ khen thưởng, phúc lợi"),
        ("356", "Quỹ phát triển khoa học và công nghệ", "no_phai_tra", "Quỹ phát triển khoa học và công nghệ"),
        ("357", "Quỹ bình ổn giá", "no_phai_tra", "Quỹ bình ổn giá"),
        # LOẠI 4 - VỐN CHỦ SỞ HỮU
        ("411", "Vốn đầu tư của chủ sở hữu", "von_chu_so_huu", "Vốn đầu tư từ các chủ sở hữu"),
        ("412", "Thặng dư vốn cổ phần", "von_chu_so_huu", "Thặng dư vốn cổ phần"),
        ("413", "Chênh lệch tỷ giá hối đoái", "von_chu_so_huu", "Chênh lệch tỷ giá hối đoái"),
        ("414", "Quỹ đầu tư phát triển", "von_chu_so_huu", "Quỹ đầu tư phát triển doanh nghiệp"),
        ("415", "Chênh lệch đánh giá lại tài sản", "von_chu_so_huu", "Chênh lệch do đánh giá lại tài sản"),
        ("418", "Các quỹ khác thuộc vốn chủ sở hữu", "von_chu_so_huu", "Các quỹ khác thuộc vốn chủ sở hữu"),
        ("419", "Cổ phiếu quỹ", "von_chu_so_huu", "Giá trị cổ phiếu do công ty mua lại"),
        ("420", "Lợi ích cổ đông thiểu số", "von_chu_so_huu", "Lợi ích cổ đông thiểu số"),
        ("421", "Lợi nhuận sau thuế chưa phân phối", "von_chu_so_huu", "Lợi nhuận sau thuế chưa phân phối cho chủ sở hữu"),
        # LOẠI 5 - DOANH THU
        ("511", "Doanh thu bán hàng và cung cấp dịch vụ", "doanh_thu", "Doanh thu từ hoạt động bán hàng và cung cấp dịch vụ"),
        ("512", "Doanh thu bán hàng nội bộ", "doanh_thu", "Doanh thu bán hàng nội bộ"),
        ("515", "Doanh thu hoạt động tài chính", "doanh_thu", "Doanh thu từ hoạt động tài chính"),
        ("521", "Các khoản giảm trừ doanh thu", "doanh_thu", "Giảm giá, chiết khấu, hàng bán bị trả lại"),
        # LOẠI 6 - CHI PHÍ
        ("621", "Chi phí nguyên liệu, vật liệu trực tiếp", "chi_phi", "Chi phí nguyên liệu, vật liệu trực tiếp sản xuất"),
        ("622", "Chi phí nhân công trực tiếp", "chi_phi", "Chi phí nhân công trực tiếp sản xuất"),
        ("623", "Chi phí sử dụng máy thi công", "chi_phi", "Chi phí sử dụng máy thi công"),
        ("627", "Chi phí sản xuất chung", "chi_phi", "Chi phí sản xuất chung"),
        ("631", "Giá thành sản xuất", "chi_phi", "Giá thành sản xuất"),
        ("632", "Giá vốn hàng bán", "chi_phi", "Giá vốn của hàng hóa, dịch vụ đã bán"),
        ("635", "Chi phí tài chính", "chi_phi", "Chi phí hoạt động tài chính (lãi vay, tỷ giá...)"),
        ("641", "Chi phí bán hàng", "chi_phi", "Chi phí phục vụ cho hoạt động bán hàng"),
        ("642", "Chi phí quản lý kinh doanh", "chi_phi", "Chi phí quản lý hành chính doanh nghiệp"),
        # LOẠI 7 - THU NHẬP KHÁC
        ("711", "Thu nhập khác", "thu_nhap_khac", "Thu nhập từ hoạt động khác"),
        # LOẠI 8 - CHI PHÍ KHÁC
        ("811", "Chi phí khác", "chi_phi_khac", "Chi phí từ hoạt động khác"),
        ("821", "Chi phí thuế TNDN", "chi_phi_khac", "Chi phí thuế thu nhập doanh nghiệp"),
        # LOẠI 9 - XÁC ĐỊNH KẾT QUẢ
        ("911", "Xác định kết quả kinh doanh", "xac_dinh_kq", "Tài khoản xác định kết quả hoạt động kinh doanh"),
    ]

    # Insert Tier-1 accounts
    for ma, ten, loai, mo_ta in tier1_accounts:
        TaiKhoanKeToan.objects.create(
            ma_tai_khoan=ma,
            ten_tai_khoan=ten,
            cap_do=1,
            loai_tai_khoan=loai,
            mo_ta=mo_ta,
            is_active=True,
            is_immutable=True,
            created_by="system",
            updated_by="system",
        )

    # Build parent lookup
    parent_lookup = {
        acc.ma_tai_khoan: acc
        for acc in TaiKhoanKeToan.objects.filter(cap_do=1)
    }

    tier2_accounts = [
        ("1281", "Đầu tư ngắn hạn", "128", "Đầu tư ngắn hạn nắm giữ đến ngày đáo hạn"),
        ("1282", "Đầu tư dài hạn", "128", "Đầu tư dài hạn nắm giữ đến ngày đáo hạn"),
        ("1283", "Dự phòng giảm giá đầu tư", "128", "Dự phòng giảm giá đầu tư nắm giữ đến ngày đáo hạn"),
        ("1288", "Đầu tư khác", "128", "Đầu tư khác nắm giữ đến ngày đáo hạn"),
        ("1331", "Thuế GTGT được khấu trừ", "133", "Thuế GTGT đầu vào được khấu trừ"),
        ("1332", "Thuế GTGT đầu vào của BĐS đầu tư", "133", "Thuế GTGT đầu vào của BĐS đầu tư được khấu trừ"),
        ("1361", "Phải thu nội bộ ngắn hạn", "136", "Phải thu nội bộ ngắn hạn"),
        ("1362", "Phải thu nội bộ dài hạn", "136", "Phải thu nội bộ dài hạn"),
        ("1363", "Phải thu nội bộ khác", "136", "Phải thu nội bộ khác"),
        ("1368", "Phải thu nội bộ chi tiết", "136", "Phải thu nội bộ chi tiết theo đối tượng"),
        ("1381", "Phải thu về tài sản thiếu", "138", "Phải thu về tài sản thiếu chờ xử lý"),
        ("1383", "Phải thu về bồi thường", "138", "Phải thu về bồi thường thiệt hại"),
        ("1388", "Phải thu khác chi tiết", "138", "Phải thu khác chi tiết theo đối tượng"),
        ("2141", "Hao mòn TSCĐ hữu hình", "214", "Hao mòn lũy kế TSCĐ hữu hình"),
        ("2142", "Hao mòn TSCĐ thuê tài chính", "214", "Hao mòn lũy kế TSCĐ thuê tài chính"),
        ("2143", "Hao mòn TSCĐ vô hình", "214", "Hao mòn lũy kế TSCĐ vô hình"),
        ("2147", "Hao mòn BĐS đầu tư", "214", "Hao mòn lũy kế BĐS đầu tư"),
        ("2151", "Tài sản sinh học ngắn hạn", "215", "Tài sản sinh học ngắn hạn"),
        ("2152", "Tài sản sinh học dài hạn", "215", "Tài sản sinh học dài hạn"),
        ("2291", "Dự phòng đầu tư CK kinh doanh", "229", "Dự phòng tổn thất đầu tư chứng khoán kinh doanh"),
        ("2292", "Dự phòng đầu tư đơn vị khác", "229", "Dự phòng tổn thất đầu tư vào đơn vị khác"),
        ("2293", "Dự phòng đầu tư nắm giữ đến đáo hạn", "229", "Dự phòng tổn thất đầu tư nắm giữ đến ngày đáo hạn"),
        ("2294", "Dự phòng tổn thất đầu tư khác", "229", "Dự phòng tổn thất đầu tư khác"),
        ("2295", "Dự phòng giảm giá đầu tư dài hạn", "229", "Dự phòng giảm giá đầu tư dài hạn"),
        ("2411", "Chi phí XDCB dở dang", "241", "Chi phí xây dựng cơ bản dở dang"),
        ("2412", "Thiết bị đang lắp đặt", "241", "Giá trị thiết bị đang lắp đặt"),
        ("2413", "Chi phí khác XDCB", "241", "Chi phí khác liên quan XDCB"),
        ("2414", "Chi phí XDCB khác", "241", "Chi phí XDCB khác"),
        ("3331", "Thuế GTGT phải nộp", "333", "Thuế GTGT phải nộp ngân sách nhà nước"),
        ("3332", "Thuế tiêu thụ đặc biệt", "333", "Thuế tiêu thụ đặc biệt phải nộp"),
        ("3333", "Thuế xuất, nhập khẩu", "333", "Thuế xuất nhập khẩu phải nộp"),
        ("3334", "Thuế thu nhập doanh nghiệp", "333", "Thuế TNDN phải nộp"),
        ("3335", "Thuế thu nhập cá nhân", "333", "Thuế TNCN phải nộp"),
        ("3336", "Thuế tài nguyên", "333", "Thuế tài nguyên phải nộp"),
        ("3337", "Thuế nhà thầu", "333", "Thuế nhà thầu phải nộp"),
        ("3338", "Thuế bảo vệ môi trường", "333", "Thuế bảo vệ môi trường phải nộp"),
        ("3339", "Các loại thuế khác", "333", "Các loại thuế khác phải nộp"),
        ("3381", "Tài sản thừa chờ giải quyết", "338", "Tài sản thừa chờ giải quyết"),
        ("3382", "Kinh phí công đoàn", "338", "Kinh phí công đoàn"),
        ("3383", "BHXH phải nộp", "338", "Bảo hiểm xã hội phải nộp"),
        ("3384", "BHYT phải nộp", "338", "Bảo hiểm y tế phải nộp"),
        ("3385", "BHTN phải nộp", "338", "Bảo hiểm thất nghiệp phải nộp"),
        ("3386", "BHTNLĐ-BNN phải nộp", "338", "Bảo hiểm TNLĐ-BNN phải nộp"),
        ("3387", "Công đoàn phí", "338", "Công đoàn phí"),
        ("3388", "Phải trả phải nộp khác", "338", "Các khoản phải trả phải nộp khác"),
        ("3411", "Vay ngắn hạn", "341", "Các khoản vay ngắn hạn"),
        ("3412", "Vay dài hạn", "341", "Các khoản vay dài hạn"),
        ("3431", "Trái phiếu thường", "343", "Giá trị trái phiếu thường đã phát hành"),
        ("3432", "Trái phiếu có quyền chọn", "343", "Giá trị trái phiếu có quyền chọn đã phát hành"),
        ("3521", "Dự phòng bảo hành sản phẩm, hàng hóa", "352", "Dự phòng bảo hành sản phẩm, hàng hóa"),
        ("3522", "Dự phòng bảo lãnh", "352", "Dự phòng bảo lãnh"),
        ("3523", "Dự phòng phải trả khác", "352", "Dự phòng phải trả khác"),
        ("3531", "Quỹ khen thưởng", "353", "Quỹ khen thưởng"),
        ("3532", "Quỹ phúc lợi", "353", "Quỹ phúc lợi"),
        ("3561", "Quỹ phát triển KH&CN ngắn hạn", "356", "Quỹ phát triển KH&CN ngắn hạn"),
        ("3562", "Quỹ phát triển KH&CN dài hạn", "356", "Quỹ phát triển KH&CN dài hạn"),
        ("4111", "Vốn góp của chủ sở hữu", "411", "Vốn góp của chủ sở hữu"),
        ("4112", "Thặng dư vốn cổ phần", "411", "Thặng dư vốn cổ phần"),
        ("4113", "Quyền chọn chuyển đổi trái phiếu", "411", "Quyền chọn chuyển đổi trái phiếu thành cổ phiếu"),
        ("4118", "Vốn khác", "411", "Vốn khác thuộc vốn chủ sở hữu"),
        ("4211", "Lợi nhuận năm trước", "421", "Lợi nhuận sau thuế chưa phân phối năm trước"),
        ("4212", "Lợi nhuận năm nay", "421", "Lợi nhuận sau thuế chưa phân phối năm nay"),
        ("5111", "Doanh thu bán hàng hóa", "511", "Doanh thu bán hàng hóa"),
        ("5112", "Doanh thu bán thành phẩm", "511", "Doanh thu bán thành phẩm"),
        ("5113", "Doanh thu cung cấp dịch vụ", "511", "Doanh thu cung cấp dịch vụ"),
        ("5114", "Doanh thu trợ cấp, trợ giá", "511", "Doanh thu trợ cấp, trợ giá"),
        ("5115", "Doanh thu bất động sản đầu tư", "511", "Doanh thu bất động sản đầu tư"),
        ("5116", "Doanh thu nhượng bán TSCĐ", "511", "Doanh thu nhượng bán TSCĐ"),
        ("5117", "Doanh thu cho thuê TSCĐ", "511", "Doanh thu cho thuê TSCĐ"),
        ("5118", "Doanh thu bản quyền", "511", "Doanh thu bản quyền"),
        ("5119", "Doanh thu khác", "511", "Doanh thu khác"),
        ("5211", "Chiết khấu thương mại", "521", "Chiết khấu thương mại"),
        ("5212", "Giảm giá hàng bán", "521", "Giảm giá hàng bán"),
        ("5213", "Hàng bán bị trả lại", "521", "Hàng bán bị trả lại"),
        ("5214", "Thuế TTĐB, thuế XK, thuế GTGT theo pp trực tiếp", "521", "Thuế TTĐB, thuế XK, thuế GTGT theo phương pháp trực tiếp"),
        ("6211", "Chi phí NVLTT", "621", "Chi phí nguyên liệu, vật liệu trực tiếp"),
        ("6221", "Chi phí NCTT", "622", "Chi phí nhân công trực tiếp"),
        ("6231", "Chi phí nhân công", "623", "Chi phí nhân công sử dụng máy thi công"),
        ("6232", "Chi phí vật liệu", "623", "Chi phí vật liệu sử dụng máy thi công"),
        ("6233", "Chi phí dụng cụ sản xuất", "623", "Chi phí dụng cụ sản xuất máy thi công"),
        ("6234", "Chi phí khấu hao máy", "623", "Chi phí khấu hao máy thi công"),
        ("6235", "Chi phí dịch vụ mua ngoài", "623", "Chi phí dịch vụ mua ngoài phục vụ máy thi công"),
        ("6236", "Chi phí bằng tiền khác", "623", "Chi phí bằng tiền khác phục vụ máy thi công"),
        ("6271", "Chi phí nhân viên phân xưởng", "627", "Chi phí nhân viên phân xưởng, đội, trại"),
        ("6272", "Chi phí vật liệu", "627", "Chi phí vật liệu sản xuất chung"),
        ("6273", "Chi phí dụng cụ", "627", "Chi phí dụng cụ sản xuất chung"),
        ("6274", "Chi phí khấu hao TSCĐ", "627", "Chi phí khấu hao TSCĐ dùng chung"),
        ("6275", "Chi phí dịch vụ mua ngoài", "627", "Chi phí dịch vụ mua ngoài phục vụ sản xuất chung"),
        ("6276", "Chi phí bằng tiền khác", "627", "Chi phí bằng tiền khác phục vụ sản xuất chung"),
        ("6421", "Chi phí nhân viên quản lý", "642", "Chi phí nhân viên quản lý"),
        ("6422", "Chi phí vật liệu quản lý", "642", "Chi phí vật liệu quản lý"),
        ("6423", "Chi phí đồ dùng văn phòng", "642", "Chi phí đồ dùng văn phòng"),
        ("6424", "Chi phí khấu hao TSCĐ", "642", "Chi phí khấu hao TSCĐ quản lý"),
        ("6425", "Thuế, phí, lệ phí", "642", "Thuế, phí, lệ phí"),
        ("6426", "Chi phí dịch vụ mua ngoài", "642", "Chi phí dịch vụ mua ngoài quản lý"),
        ("6427", "Chi phí bằng tiền khác", "642", "Chi phí bằng tiền khác quản lý"),
        ("6428", "Chi phí khác", "642", "Chi phí quản lý khác"),
        ("8211", "Chi phí thuế TNDN hiện hành", "821", "Chi phí thuế TNDN hiện hành"),
        ("8212", "Chi phí thuế TNDN hoãn lại", "821", "Chi phí thuế TNDN hoãn lại"),
    ]

    # Insert Tier-2 accounts
    for ma, ten, parent_code, mo_ta in tier2_accounts:
        parent = parent_lookup.get(parent_code)
        if parent:
            TaiKhoanKeToan.objects.create(
                ma_tai_khoan=ma,
                ten_tai_khoan=ten,
                cap_do=2,
                tai_khoan_me=parent,
                loai_tai_khoan=parent.loai_tai_khoan,
                mo_ta=mo_ta,
                is_active=True,
                is_immutable=True,
                created_by="system",
                updated_by="system",
            )


def remove_seed_coa(apps, schema_editor):
    """Remove all seeded accounts."""
    TaiKhoanKeToan = apps.get_model("danh_muc", "TaiKhoanKeToan")
    TaiKhoanKeToan.objects.filter(created_by="system").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("danh_muc", "0004_alter_taikhoanketoan_loai_tai_khoan"),
    ]

    operations = [
        migrations.RunPython(seed_coa_tt99, remove_seed_coa),
    ]
