# Generated by Django 5.2.12 on 2026-04-03
# Fix COA to comply with TT 99/2025/TT-BTC

from django.db import migrations


def fix_coa_tt99_compliance(apps, schema_editor):
    """
    Fix Chart of Accounts to comply with TT 99/2025/TT-BTC Phụ lục II.
    
    Changes:
    1. 155: Thành phẩm → Sản phẩm
    2. 215: TSCĐ thuê tài sản → Tài sản sinh học
    3. 339 → 332 (change code)
    4. 413: Vốn khác của chủ sở hữu → Chênh lệch tỷ giá hối đoái
    5. 414: Cổ phiếu quỹ → Quỹ đầu tư phát triển
    6. 419: Cổ phiếu ưu đãi → Cổ phiếu quỹ
    7. Add missing: 158, 171, 344, 352, 353, 356, 357, 821
    8. Update Tier-2 accounts for 215, 352, 353, 356
    """
    TaiKhoanKeToan = apps.get_model("danh_muc", "TaiKhoanKeToan")

    # 1. Fix 155: Thành phẩm → Sản phẩm
    tk155 = TaiKhoanKeToan.objects.filter(ma_tai_khoan="155").first()
    if tk155:
        tk155.ten_tai_khoan = "Sản phẩm"
        tk155.mo_ta = "Sản phẩm tồn kho"
        tk155.save()

    # 2. Fix 215: TSCĐ thuê tài sản → Tài sản sinh học
    tk215 = TaiKhoanKeToan.objects.filter(ma_tai_khoan="215").first()
    if tk215:
        tk215.ten_tai_khoan = "Tài sản sinh học"
        tk215.mo_ta = "Tài sản sinh học"
        tk215.save()
        # Update Tier-2 accounts under 215
        TaiKhoanKeToan.objects.filter(ma_tai_khoan="2151").update(
            ten_tai_khoan="Tài sản sinh học ngắn hạn",
            mo_ta="Tài sản sinh học ngắn hạn"
        )
        TaiKhoanKeToan.objects.filter(ma_tai_khoan="2152").update(
            ten_tai_khoan="Tài sản sinh học dài hạn",
            mo_ta="Tài sản sinh học dài hạn"
        )
        TaiKhoanKeToan.objects.filter(ma_tai_khoan="2153").delete()

    # 3. Fix 339 → 332 (change account code)
    tk339 = TaiKhoanKeToan.objects.filter(ma_tai_khoan="339").first()
    if tk339:
        # Check if 332 already exists
        tk332 = TaiKhoanKeToan.objects.filter(ma_tai_khoan="332").first()
        if tk332:
            # Delete 339, update 332
            tk339.delete()
        else:
            # Rename 339 to 332
            tk339.ma_tai_khoan = "332"
            tk339.ten_tai_khoan = "Phải trả cổ tức, lợi nhuận"
            tk339.mo_ta = "Phải trả cổ tức, lợi nhuận cho chủ sở hữu"
            tk339.save()

    # 4. Fix 413: Vốn khác → Chênh lệch tỷ giá hối đoái
    tk413 = TaiKhoanKeToan.objects.filter(ma_tai_khoan="413").first()
    if tk413:
        tk413.ten_tai_khoan = "Chênh lệch tỷ giá hối đoái"
        tk413.mo_ta = "Chênh lệch tỷ giá hối đoái"
        tk413.save()

    # 5. Fix 414: Cổ phiếu quỹ → Quỹ đầu tư phát triển
    tk414 = TaiKhoanKeToan.objects.filter(ma_tai_khoan="414").first()
    if tk414:
        tk414.ten_tai_khoan = "Quỹ đầu tư phát triển"
        tk414.mo_ta = "Quỹ đầu tư phát triển doanh nghiệp"
        tk414.save()

    # 6. Fix 419: Cổ phiếu ưu đãi → Cổ phiếu quỹ
    tk419 = TaiKhoanKeToan.objects.filter(ma_tai_khoan="419").first()
    if tk419:
        tk419.ten_tai_khoan = "Cổ phiếu quỹ"
        tk419.mo_ta = "Giá trị cổ phiếu do công ty mua lại"
        tk419.save()

    # 7. Add missing accounts
    missing_tier1 = [
        ("158", "Nguyên liệu, vật tư tại kho bảo thuế", "tai_san", "Nguyên liệu, vật tư tại kho bảo thuế"),
        ("171", "Giao dịch mua, bán lại trái phiếu chính phủ", "tai_san", "Giao dịch mua, bán lại trái phiếu chính phủ"),
        ("344", "Nhận ký quỹ, ký cược", "no_phai_tra", "Tiền và tài sản nhận ký quỹ, ký cược"),
        ("352", "Dự phòng phải trả", "no_phai_tra", "Dự phòng phải trả"),
        ("353", "Quỹ khen thưởng, phúc lợi", "no_phai_tra", "Quỹ khen thưởng, phúc lợi"),
        ("356", "Quỹ phát triển khoa học và công nghệ", "no_phai_tra", "Quỹ phát triển khoa học và công nghệ"),
        ("357", "Quỹ bình ổn giá", "no_phai_tra", "Quỹ bình ổn giá"),
        ("821", "Chi phí thuế thu nhập doanh nghiệp", "chi_phi_khac", "Chi phí thuế thu nhập doanh nghiệp"),
    ]

    for ma, ten, loai, mo_ta in missing_tier1:
        existing = TaiKhoanKeToan.objects.filter(ma_tai_khoan=ma).first()
        if not existing:
            TaiKhoanKeToan.objects.create(
                ma_tai_khoan=ma,
                ten_tai_khoan=ten,
                cap_do=1,
                loai_tai_khoan=loai,
                mo_ta=mo_ta,
                is_active=True,
                is_immutable=True,
                created_by="system",
                updated_by="system",
            )

    # 8. Add Tier-2 accounts for new parents
    parent_lookup = {
        acc.ma_tai_khoan: acc
        for acc in TaiKhoanKeToan.objects.filter(cap_do=1)
    }

    tier2_accounts = [
        # Under 352 - Dự phòng phải trả
        ("3521", "Dự phòng bảo hành sản phẩm, hàng hóa", "352", "Dự phòng bảo hành sản phẩm, hàng hóa"),
        ("3522", "Dự phòng bảo lãnh", "352", "Dự phòng bảo lãnh"),
        ("3523", "Dự phòng phải trả khác", "352", "Dự phòng phải trả khác"),
        # Under 353 - Quỹ khen thưởng, phúc lợi
        ("3531", "Quỹ khen thưởng", "353", "Quỹ khen thưởng"),
        ("3532", "Quỹ phúc lợi", "353", "Quỹ phúc lợi"),
        # Under 356 - Quỹ phát triển khoa học và công nghệ
        ("3561", "Quỹ phát triển KH&CN ngắn hạn", "356", "Quỹ phát triển KH&CN ngắn hạn"),
        ("3562", "Quỹ phát triển KH&CN dài hạn", "356", "Quỹ phát triển KH&CN dài hạn"),
    ]

    for ma, ten, parent_code, mo_ta in tier2_accounts:
        existing = TaiKhoanKeToan.objects.filter(ma_tai_khoan=ma).first()
        if not existing:
            parent = parent_lookup.get(parent_code)
            if parent:
                TaiKhoanKeToan.objects.create(
                    ma_tai_khoan=ma,
                    ten_tai_khoan=ten,
                    cap_do=2,
                    tai_khoan_me=parent,
                    loai_tai_khoan=parent.loai_tai_khoan,
                    mo_ta=mo_ta,
                    is_active=True,
                    is_immutable=True,
                    created_by="system",
                    updated_by="system",
                )

    # 9. Add 821 Tier-2
    tk821 = TaiKhoanKeToan.objects.filter(ma_tai_khoan="821").first()
    if tk821:
        tier2_821 = [
            ("8211", "Chi phí thuế TNDN hiện hành", "821", "Chi phí thuế TNDN hiện hành"),
            ("8212", "Chi phí thuế TNDN hoãn lại", "821", "Chi phí thuế TNDN hoãn lại"),
        ]
        for ma, ten, parent_code, mo_ta in tier2_821:
            existing = TaiKhoanKeToan.objects.filter(ma_tai_khoan=ma).first()
            if not existing:
                TaiKhoanKeToan.objects.create(
                    ma_tai_khoan=ma,
                    ten_tai_khoan=ten,
                    cap_do=2,
                    tai_khoan_me=tk821,
                    loai_tai_khoan="chi_phi_khac",
                    mo_ta=mo_ta,
                    is_active=True,
                    is_immutable=True,
                    created_by="system",
                    updated_by="system",
                )


def reverse_coa(apps, schema_editor):
    """Reverse migration - restore original COA."""
    TaiKhoanKeToan = apps.get_model("danh_muc", "TaiKhoanKeToan")
    # Delete added accounts
    for code in ["158", "171", "344", "352", "353", "356", "357"]:
        TaiKhoanKeToan.objects.filter(ma_tai_khoan=code).delete()
    for code in ["3521", "3522", "3523", "3531", "3532", "3561", "3562", "8211", "8212"]:
        TaiKhoanKeToan.objects.filter(ma_tai_khoan=code).delete()
    # Restore 339
    tk332 = TaiKhoanKeToan.objects.filter(ma_tai_khoan="332").first()
    if tk332:
        tk332.ma_tai_khoan = "339"
        tk332.ten_tai_khoan = "Phải trả cổ tức, lợi nhuận"
        tk332.save()


class Migration(migrations.Migration):

    dependencies = [
        ("danh_muc", "0006_update_account_157_tt99"),
    ]

    operations = [
        migrations.RunPython(fix_coa_tt99_compliance, reverse_coa),
    ]