# Generated by Django 6.0.3 on 2026-04-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('danh_muc', '0004_alter_taikhoanketoan_loai_tai_khoan'),
        ('nghiep_vu', '0005_buttoan_ngay_dua_vao_su_dung_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienBanDoiChieuCongNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi_tuong_object_id', models.PositiveIntegerField(verbose_name='ID đối tượng')),
                ('loai', models.CharField(choices=[('phai_thu', 'Phải thu'), ('phai_tra', 'Phải trả')], max_length=10, verbose_name='Loại')),
                ('thang', models.IntegerField(verbose_name='Tháng')),
                ('nam', models.IntegerField(verbose_name='Năm')),
                ('so_dau_ky', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Số dư đầu kỳ')),
                ('phat_sinh_no', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Phát sinh Nợ')),
                ('phat_sinh_co', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Phát sinh Có')),
                ('so_cuoi_ky', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Số dư cuối kỳ')),
                ('da_xac_nhan', models.BooleanField(default=False, verbose_name='Đã xác nhận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('doi_tuong_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Loại đối tượng')),
            ],
            options={
                'verbose_name': 'Biên bản đối chiếu công nợ',
                'verbose_name_plural': 'Biên bản đối chiếu công nợ',
                'ordering': ['-nam', '-thang'],
            },
        ),
        migrations.CreateModel(
            name='CongNoPhaiThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_no', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tổng nợ')),
                ('da_thu', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Đã thu')),
                ('con_no', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Còn nợ')),
                ('ngay_den_han', models.DateField(blank=True, null=True, verbose_name='Ngày đến hạn')),
                ('qua_han', models.BooleanField(default=False, verbose_name='Quá hạn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('hoa_don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cong_no_phai_thu', to='nghiep_vu.hoadon', verbose_name='Hóa đơn')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cong_no_phai_thu', to='danh_muc.khachhang', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Công nợ phải thu',
                'verbose_name_plural': 'Công nợ phải thu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CongNoPhaiTra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_no', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tổng nợ')),
                ('da_tra', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Đã trả')),
                ('con_no', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Còn nợ')),
                ('ngay_den_han', models.DateField(blank=True, null=True, verbose_name='Ngày đến hạn')),
                ('qua_han', models.BooleanField(default=False, verbose_name='Quá hạn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('chung_tu_goc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cong_no_phai_tra', to='nghiep_vu.nhapkho', verbose_name='Chứng từ gốc')),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cong_no_phai_tra', to='danh_muc.nhacungcap', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Công nợ phải trả',
                'verbose_name_plural': 'Công nợ phải trả',
                'ordering': ['-created_at'],
            },
        ),
    ]
