# Generated by Django 6.0.3 on 2026-04-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('danh_muc', '0004_alter_taikhoanketoan_loai_tai_khoan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongCuDungCu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ccdc', models.CharField(max_length=20, unique=True, verbose_name='Mã CCDC')),
                ('ten_ccdc', models.CharField(max_length=255, verbose_name='Tên CCDC')),
                ('ngay_mua', models.DateField(verbose_name='Ngày mua')),
                ('so_luong', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Số lượng')),
                ('gia_mua', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Giá mua')),
                ('tong_gia_tri', models.DecimalField(decimal_places=2, help_text='Giá mua × Số lượng', max_digits=20, verbose_name='Tổng giá trị')),
                ('phuong_phap_phan_bo', models.CharField(choices=[('1_lan', 'Phân bổ 1 lần'), ('nhieu_lan', 'Phân bổ nhiều lần')], default='nhieu_lan', max_length=10, verbose_name='Phương pháp phân bổ')),
                ('so_ky_phan_bo', models.IntegerField(default=1, verbose_name='Số kỳ phân bổ')),
                ('ky_phan_bo_bat_dau', models.DateField(verbose_name='Kỳ phân bổ bắt đầu')),
                ('ky_phan_bo_ket_thuc', models.DateField(verbose_name='Kỳ phân bổ kết thúc')),
                ('trang_thai', models.CharField(choices=[('dang_theo_doi', 'Đang theo dõi'), ('da_phan_bo_het', 'Đã phân bổ hết'), ('thanh_ly', 'Đã thanh lý')], default='dang_theo_doi', max_length=15, verbose_name='Trạng thái')),
                ('dien_giai', models.TextField(blank=True, default='', verbose_name='Diễn giải')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Người tạo')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Người cập nhật')),
                ('tk_chi_phi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ccdc_chi_phi', to='danh_muc.taikhoanketoan', verbose_name='TK chi phí')),
            ],
            options={
                'verbose_name': 'Công cụ dụng cụ',
                'verbose_name_plural': 'Công cụ dụng cụ',
                'ordering': ['ma_ccdc'],
            },
        ),
        migrations.CreateModel(
            name='BangPhanBoCCDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.IntegerField(verbose_name='Tháng')),
                ('nam', models.IntegerField(verbose_name='Năm')),
                ('so_tien_phan_bo', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số tiền phân bổ')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('da_hach_toan', 'Đã hạch toán')], default='draft', max_length=12, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ccdc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bang_phan_bo', to='ccdc.congcudungcu', verbose_name='CCDC')),
            ],
            options={
                'verbose_name': 'Bảng phân bổ CCDC',
                'verbose_name_plural': 'Bảng phân bổ CCDC',
                'ordering': ['nam', 'thang'],
                'unique_together': {('ccdc', 'thang', 'nam')},
            },
        ),
    ]
