# Generated by Django 6.0.3 on 2026-04-03 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("he_thong", "0002_vaitro"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nguoidung",
            name="vai_tro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nguoi_dung",
                to="he_thong.vaitro",
                verbose_name="Vai trò",
            ),
        ),
    ]
