# Generated by Django 6.0.3 on 2026-04-02 09:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nghiep_vu', '0005_buttoan_ngay_dua_vao_su_dung_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KiemKeQuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_kiem_ke', models.CharField(max_length=50, unique=True, verbose_name='Số kiểm kê')),
                ('ngay_kiem_ke', models.DateField(verbose_name='Ngày kiểm kê')),
                ('ky_quy', models.CharField(help_text='VD: Q1/2026, T01/2026', max_length=20, verbose_name='Kỳ quỹ')),
                ('so_du_so_sach', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số dư sổ sách')),
                ('so_thuc_te', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số thực tế')),
                ('chen_lech', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto: thực tế - sổ sách', max_digits=20, verbose_name='Chênh lệch')),
                ('ly_do', models.TextField(blank=True, default='', verbose_name='Lý do')),
                ('nguoi_kiem_ke', models.CharField(max_length=200, verbose_name='Người kiểm kê')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('da_xu_ly', 'Đã xử lý')], default='draft', max_length=15, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('thu_quy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kiem_ke_quy', to=settings.AUTH_USER_MODEL, verbose_name='Thủ quỹ')),
            ],
            options={
                'verbose_name': 'Kiểm kê quỹ',
                'verbose_name_plural': 'Kiểm kê quỹ',
                'ordering': ['-ngay_kiem_ke'],
            },
        ),
        migrations.CreateModel(
            name='XuLyChenhLechQuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('thieu', 'Thiếu quỹ'), ('thua', 'Thừa quỹ')], max_length=10, verbose_name='Loại chênh lệch')),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số tiền')),
                ('nguyen_nhan', models.TextField(verbose_name='Nguyên nhân')),
                ('xu_ly', models.CharField(choices=[('bo_thuong', 'Bồi thường'), ('ghi_giam_chi_phi', 'Ghi giảm chi phí'), ('ghi_tang_thu_nhap', 'Ghi tăng thu nhập')], max_length=30, verbose_name='Hình thức xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('but_toan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xu_ly_chenh_lech', to='nghiep_vu.buttoan', verbose_name='Bút toán xử lý')),
                ('kiem_ke', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xu_ly_chenh_lech', to='thu_quy.kiemkequy', verbose_name='Kiểm kê')),
            ],
            options={
                'verbose_name': 'Xử lý chênh lệch quỹ',
                'verbose_name_plural': 'Xử lý chênh lệch quỹ',
                'ordering': ['-created_at'],
            },
        ),
    ]
