# Generated by Django 6.0.3 on 2026-04-02 09:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('danh_muc', '0004_alter_taikhoanketoan_loai_tai_khoan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BangPhanBoChiPhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.IntegerField(verbose_name='Tháng')),
                ('nam', models.IntegerField(verbose_name='Năm')),
                ('phuong_phap', models.CharField(choices=[('truc_tiep', 'Trực tiếp'), ('he_so', 'Hệ số'), ('ty_le', 'Tỷ lệ'), ('dinh_muc', 'Định mức')], max_length=20, verbose_name='Phương pháp phân bổ')),
                ('tieu_thuc_phan_bo', models.CharField(choices=[('gio_cong', 'Giờ công'), ('gio_may', 'Giờ máy'), ('chi_phi_nvl', 'Chi phí NLVL'), ('chi_phi_truc_tiep', 'Chi phí trực tiếp')], max_length=30, verbose_name='Tiêu thức phân bổ')),
                ('tong_chi_phi', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Tổng chi phí')),
                ('dien_giai', models.TextField(blank=True, default='', verbose_name='Diễn giải')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('posted', 'Đã ghi sổ')], default='draft', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Bảng phân bổ chi phí',
                'verbose_name_plural': 'Bảng phân bổ chi phí',
                'ordering': ['-nam', '-thang'],
            },
        ),
        migrations.CreateModel(
            name='DoiTuongTapHopChiPhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_doi_tuong', models.CharField(max_length=20, unique=True, verbose_name='Mã đối tượng')),
                ('ten_doi_tuong', models.CharField(max_length=200, verbose_name='Tên đối tượng')),
                ('loai', models.CharField(choices=[('san_pham', 'Sản phẩm'), ('don_hang', 'Đơn hàng'), ('phan_xuong', 'Phân xưởng')], max_length=20, verbose_name='Loại đối tượng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('san_pham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doi_tuong_chi_phi', to='danh_muc.hanghoa', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Đối tượng tập hợp chi phí',
                'verbose_name_plural': 'Đối tượng tập hợp chi phí',
                'ordering': ['ma_doi_tuong'],
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhanBoChiPhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('he_so', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, verbose_name='Hệ số')),
                ('muc_phan_bo', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Mức phân bổ')),
                ('dien_giai', models.TextField(blank=True, default='', verbose_name='Diễn giải')),
                ('bang_phan_bo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_phan_bo', to='gia_thanh.bangphanbochiphi', verbose_name='Bảng phân bổ')),
                ('doi_tuong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gia_thanh.doituongtaphopchiphi', verbose_name='Đối tượng')),
            ],
            options={
                'verbose_name': 'Chi tiết phân bổ chi phí',
                'verbose_name_plural': 'Chi tiết phân bổ chi phí',
            },
        ),
        migrations.CreateModel(
            name='BangTinhGiaThanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.IntegerField(verbose_name='Tháng')),
                ('nam', models.IntegerField(verbose_name='Năm')),
                ('cp_dở_dang_dau_ky', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='CP dở dang đầu kỳ')),
                ('cp_phat_sinh', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='CP phát sinh trong kỳ')),
                ('cp_dở_dang_cuoi_ky', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='CP dở dang cuối kỳ')),
                ('gia_thanh_sp_hoan_thanh', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Giá thành SP hoàn thành')),
                ('so_luong_sp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Số lượng SP')),
                ('gia_thanh_don_vi', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20, verbose_name='Giá thành đơn vị')),
                ('dien_giai', models.TextField(blank=True, default='', verbose_name='Diễn giải')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('posted', 'Đã ghi sổ')], default='draft', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('doi_tuong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bang_tinh_gia_thanh', to='gia_thanh.doituongtaphopchiphi', verbose_name='Đối tượng')),
            ],
            options={
                'verbose_name': 'Bảng tính giá thành',
                'verbose_name_plural': 'Bảng tính giá thành',
                'ordering': ['-nam', '-thang'],
            },
        ),
        migrations.CreateModel(
            name='KhoanMucChiPhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_khoan_muc', models.CharField(max_length=20, unique=True, verbose_name='Mã khoản mục')),
                ('ten_khoan_muc', models.CharField(max_length=200, verbose_name='Tên khoản mục')),
                ('loai', models.CharField(choices=[('nguyen_vat_lieu', 'Nguyên vật liệu trực tiếp'), ('nhan_cong', 'Nhân công trực tiếp'), ('san_xuat_chung', 'Chi phí sản xuất chung')], max_length=30, verbose_name='Loại khoản mục')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('tk_chi_phi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khoan_muc_chi_phi', to='danh_muc.taikhoanketoan', verbose_name='TK chi phí')),
            ],
            options={
                'verbose_name': 'Khoản mục chi phí',
                'verbose_name_plural': 'Khoản mục chi phí',
                'ordering': ['ma_khoan_muc'],
            },
        ),
        migrations.CreateModel(
            name='PhieuTapHopChiPhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_chung_tu', models.CharField(max_length=50, unique=True, verbose_name='Số chứng từ')),
                ('ngay_chung_tu', models.DateField(verbose_name='Ngày chứng từ')),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số tiền')),
                ('dien_giai', models.TextField(blank=True, default='', verbose_name='Diễn giải')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('posted', 'Đã ghi sổ')], default='draft', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('doi_tuong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_tap_hop', to='gia_thanh.doituongtaphopchiphi', verbose_name='Đối tượng')),
                ('khoan_muc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_tap_hop', to='gia_thanh.khoanmucchiphi', verbose_name='Khoản mục')),
            ],
            options={
                'verbose_name': 'Phiếu tập hợp chi phí',
                'verbose_name_plural': 'Phiếu tập hợp chi phí',
                'ordering': ['-ngay_chung_tu'],
            },
        ),
    ]
