# Generated by Django 5.2.12 on 2026-03-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhieuChi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_chung_tu",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số chứng từ"
                    ),
                ),
                ("ngay_chung_tu", models.DateField(verbose_name="Ngày chứng từ")),
                (
                    "loai_chung_tu",
                    models.CharField(
                        choices=[
                            ("phieu_thu", "Phiếu thu"),
                            ("phieu_chi", "Phiếu chi"),
                            ("hoa_don", "Hóa đơn"),
                            ("chung_tu_khac", "Chứng từ khác"),
                        ],
                        max_length=20,
                        verbose_name="Loại chứng từ",
                    ),
                ),
                (
                    "dien_giai",
                    models.TextField(blank=True, default="", verbose_name="Diễn giải"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "so_tien",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Số tiền"
                    ),
                ),
                (
                    "tk_no",
                    models.CharField(
                        help_text="Tài khoản ghi Nợ",
                        max_length=10,
                        verbose_name="TK Nợ",
                    ),
                ),
                (
                    "tk_co",
                    models.CharField(
                        help_text="Tài khoản ghi Có",
                        max_length=10,
                        verbose_name="TK Có",
                    ),
                ),
                (
                    "nha_cung_cap",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nhà cung cấp",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu chi",
                "verbose_name_plural": "Phiếu chi",
                "ordering": ["-ngay_chung_tu"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhieuThu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_chung_tu",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số chứng từ"
                    ),
                ),
                ("ngay_chung_tu", models.DateField(verbose_name="Ngày chứng từ")),
                (
                    "loai_chung_tu",
                    models.CharField(
                        choices=[
                            ("phieu_thu", "Phiếu thu"),
                            ("phieu_chi", "Phiếu chi"),
                            ("hoa_don", "Hóa đơn"),
                            ("chung_tu_khac", "Chứng từ khác"),
                        ],
                        max_length=20,
                        verbose_name="Loại chứng từ",
                    ),
                ),
                (
                    "dien_giai",
                    models.TextField(blank=True, default="", verbose_name="Diễn giải"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "so_tien",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Số tiền"
                    ),
                ),
                (
                    "tk_no",
                    models.CharField(
                        help_text="Tài khoản ghi Nợ",
                        max_length=10,
                        verbose_name="TK Nợ",
                    ),
                ),
                (
                    "tk_co",
                    models.CharField(
                        help_text="Tài khoản ghi Có",
                        max_length=10,
                        verbose_name="TK Có",
                    ),
                ),
                (
                    "khach_hang",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Khách hàng",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu thu",
                "verbose_name_plural": "Phiếu thu",
                "ordering": ["-ngay_chung_tu"],
                "abstract": False,
            },
        ),
    ]
