# Generated by Django 5.1.7 on 2026-03-31 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("danh_muc", "0003_khachhang_nganhang_nhacungcap_hanghoa_and_more"),
        ("nghiep_vu", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_kho",
                    models.CharField(max_length=20, unique=True, verbose_name="Mã kho"),
                ),
                ("ten_kho", models.CharField(max_length=255, verbose_name="Tên kho")),
                (
                    "dia_chi",
                    models.TextField(blank=True, default="", verbose_name="Địa chỉ"),
                ),
                (
                    "nguoi_phu_trach",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Người phụ trách",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kho",
                "verbose_name_plural": "Kho",
                "ordering": ["ma_kho"],
            },
        ),
        migrations.CreateModel(
            name="ButToan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_but_toan",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số bút toán"
                    ),
                ),
                ("ngay_hach_toan", models.DateField(verbose_name="Ngày hạch toán")),
                (
                    "dien_giai",
                    models.TextField(blank=True, default="", verbose_name="Diễn giải"),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[("draft", "Nháp"), ("posted", "Đã ghi sổ")],
                        default="draft",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
                (
                    "nguoi_tao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="but_toan",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bút toán",
                "verbose_name_plural": "Bút toán",
                "ordering": ["-ngay_hach_toan"],
            },
        ),
        migrations.CreateModel(
            name="ButToanChiTiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loai_no_co",
                    models.CharField(
                        choices=[("no", "Nợ"), ("co", "Có")],
                        max_length=2,
                        verbose_name="Loại Nợ/Có",
                    ),
                ),
                (
                    "so_tien",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Số tiền"
                    ),
                ),
                (
                    "ma_doi_tuong",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Mã đối tượng",
                    ),
                ),
                (
                    "dien_giai",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Diễn giải"
                    ),
                ),
                (
                    "but_toan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chi_tiet",
                        to="nghiep_vu.buttoan",
                        verbose_name="Bút toán",
                    ),
                ),
                (
                    "tai_khoan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="danh_muc.taikhoanketoan",
                        verbose_name="Tài khoản",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết bút toán",
                "verbose_name_plural": "Chi tiết bút toán",
            },
        ),
        migrations.CreateModel(
            name="HoaDon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_hoa_don",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số hóa đơn"
                    ),
                ),
                (
                    "ky_hieu",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Ký hiệu"
                    ),
                ),
                ("ngay_hoa_don", models.DateField(verbose_name="Ngày hóa đơn")),
                (
                    "nguoi_mua_hang",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Người mua hàng",
                    ),
                ),
                (
                    "ma_so_thue_mua",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Mã số thuế người mua",
                    ),
                ),
                (
                    "dia_chi_mua",
                    models.TextField(
                        blank=True, default="", verbose_name="Địa chỉ người mua"
                    ),
                ),
                (
                    "hinh_thuc_thanh_toan",
                    models.CharField(
                        choices=[
                            ("tien_mat", "Tiền mặt"),
                            ("chuyen_khoan", "Chuyển khoản"),
                        ],
                        default="tien_mat",
                        max_length=20,
                        verbose_name="Hình thức thanh toán",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("issued", "Đã xuất"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "tong_tien_truoc_thue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Tổng trước thuế",
                    ),
                ),
                (
                    "tien_thue_gtgt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Tiền thuế GTGT",
                    ),
                ),
                (
                    "tong_cong_thanh_toan",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Tổng thanh toán",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
                (
                    "khach_hang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hoa_don",
                        to="danh_muc.khachhang",
                        verbose_name="Khách hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hóa đơn",
                "verbose_name_plural": "Hóa đơn",
                "ordering": ["-ngay_hoa_don"],
            },
        ),
        migrations.CreateModel(
            name="HoaDonChiTiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_luong",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Số lượng"
                    ),
                ),
                (
                    "don_gia",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Đơn giá"
                    ),
                ),
                (
                    "thue_suat",
                    models.CharField(
                        default="10", max_length=2, verbose_name="Thuế suất"
                    ),
                ),
                (
                    "tien_thue",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Tiền thuế"
                    ),
                ),
                (
                    "tong_tien",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Tổng tiền"
                    ),
                ),
                (
                    "hang_hoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="danh_muc.hanghoa",
                        verbose_name="Hàng hóa",
                    ),
                ),
                (
                    "hoa_don",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chi_tiet",
                        to="nghiep_vu.hoadon",
                        verbose_name="Hóa đơn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết hóa đơn",
                "verbose_name_plural": "Chi tiết hóa đơn",
            },
        ),
        migrations.CreateModel(
            name="NhapKho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_chung_tu",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số chứng từ"
                    ),
                ),
                ("ngay", models.DateField(verbose_name="Ngày")),
                (
                    "tong_tien",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("completed", "Hoàn thành"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
                (
                    "kho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nhap_kho",
                        to="nghiep_vu.kho",
                        verbose_name="Kho",
                    ),
                ),
                (
                    "nha_cung_cap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nhap_kho",
                        to="danh_muc.nhacungcap",
                        verbose_name="Nhà cung cấp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhập kho",
                "verbose_name_plural": "Nhập kho",
                "ordering": ["-ngay"],
            },
        ),
        migrations.CreateModel(
            name="NhapKhoChiTiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_luong",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Số lượng"
                    ),
                ),
                (
                    "don_gia",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Đơn giá"
                    ),
                ),
                (
                    "thanh_tien",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Thành tiền"
                    ),
                ),
                (
                    "hang_hoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="danh_muc.hanghoa",
                        verbose_name="Hàng hóa",
                    ),
                ),
                (
                    "nhap_kho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chi_tiet",
                        to="nghiep_vu.nhapkho",
                        verbose_name="Nhập kho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết nhập kho",
                "verbose_name_plural": "Chi tiết nhập kho",
            },
        ),
        migrations.CreateModel(
            name="XuatKho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_chung_tu",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Số chứng từ"
                    ),
                ),
                ("ngay", models.DateField(verbose_name="Ngày")),
                (
                    "tong_tien",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("completed", "Hoàn thành"),
                            ("cancelled", "Đã hủy"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
                (
                    "khach_hang",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="xuat_kho",
                        to="danh_muc.khachhang",
                        verbose_name="Khách hàng",
                    ),
                ),
                (
                    "kho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="xuat_kho",
                        to="nghiep_vu.kho",
                        verbose_name="Kho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xuất kho",
                "verbose_name_plural": "Xuất kho",
                "ordering": ["-ngay"],
            },
        ),
        migrations.CreateModel(
            name="XuatKhoChiTiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_luong",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Số lượng"
                    ),
                ),
                (
                    "don_gia",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Đơn giá"
                    ),
                ),
                (
                    "thanh_tien",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Thành tiền"
                    ),
                ),
                (
                    "hang_hoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="danh_muc.hanghoa",
                        verbose_name="Hàng hóa",
                    ),
                ),
                (
                    "xuat_kho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chi_tiet",
                        to="nghiep_vu.xuatkho",
                        verbose_name="Xuất kho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết xuất kho",
                "verbose_name_plural": "Chi tiết xuất kho",
            },
        ),
    ]
