# Generated by Django 5.2.12 on 2026-04-01 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("danh_muc", "0003_khachhang_nganhang_nhacungcap_hanghoa_and_more"),
        ("nghiep_vu", "0002_kho_buttoan_buttoanchitiet_hoadon_hoadonchitiet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phieuchi",
            name="hinh_thuc_thanh_toan",
            field=models.CharField(
                choices=[
                    ("tien_mat", "Tiền mặt (111)"),
                    ("chuyen_khoan", "Chuyển khoản (112)"),
                ],
                default="tien_mat",
                max_length=20,
                verbose_name="Hình thức thanh toán",
            ),
        ),
        migrations.AddField(
            model_name="phieuchi",
            name="so_tien_vnd",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Số tiền quy đổi sang VND",
                max_digits=20,
                verbose_name="Số tiền VND",
            ),
        ),
        migrations.AddField(
            model_name="phieuchi",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("draft", "Nháp"),
                    ("posted", "Đã ghi sổ"),
                    ("cancelled", "Đã hủy"),
                ],
                default="draft",
                max_length=10,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AddField(
            model_name="phieuchi",
            name="ty_gia",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="Tỷ giá quy đổi sang VND (mặc định 1)",
                max_digits=20,
                verbose_name="Tỷ giá",
            ),
        ),
        migrations.AddField(
            model_name="phieuthu",
            name="hinh_thuc_thanh_toan",
            field=models.CharField(
                choices=[
                    ("tien_mat", "Tiền mặt (111)"),
                    ("chuyen_khoan", "Chuyển khoản (112)"),
                ],
                default="tien_mat",
                max_length=20,
                verbose_name="Hình thức thanh toán",
            ),
        ),
        migrations.AddField(
            model_name="phieuthu",
            name="so_tien_vnd",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Số tiền quy đổi sang VND",
                max_digits=20,
                verbose_name="Số tiền VND",
            ),
        ),
        migrations.AddField(
            model_name="phieuthu",
            name="trang_thai",
            field=models.CharField(
                choices=[
                    ("draft", "Nháp"),
                    ("posted", "Đã ghi sổ"),
                    ("cancelled", "Đã hủy"),
                ],
                default="draft",
                max_length=10,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AddField(
            model_name="phieuthu",
            name="ty_gia",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="Tỷ giá quy đổi sang VND (mặc định 1)",
                max_digits=20,
                verbose_name="Tỷ giá",
            ),
        ),
        migrations.AlterField(
            model_name="phieuchi",
            name="nha_cung_cap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="phieu_chi",
                to="danh_muc.nhacungcap",
                verbose_name="Nhà cung cấp",
            ),
        ),
        migrations.AlterField(
            model_name="phieuchi",
            name="tk_co",
            field=models.CharField(
                help_text="Tài khoản ghi Có (111 hoặc 112)",
                max_length=10,
                verbose_name="TK Có",
            ),
        ),
        migrations.AlterField(
            model_name="phieuchi",
            name="tk_no",
            field=models.CharField(
                help_text="Tài khoản ghi Nợ (331, 642, ...)",
                max_length=10,
                verbose_name="TK Nợ",
            ),
        ),
        migrations.AlterField(
            model_name="phieuthu",
            name="khach_hang",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="phieu_thu",
                to="danh_muc.khachhang",
                verbose_name="Khách hàng",
            ),
        ),
        migrations.AlterField(
            model_name="phieuthu",
            name="tk_co",
            field=models.CharField(
                help_text="Tài khoản ghi Có (131, 511, ...)",
                max_length=10,
                verbose_name="TK Có",
            ),
        ),
        migrations.AlterField(
            model_name="phieuthu",
            name="tk_no",
            field=models.CharField(
                help_text="Tài khoản ghi Nợ (111 hoặc 112)",
                max_length=10,
                verbose_name="TK Nợ",
            ),
        ),
    ]
