# Generated by Django 5.2.12 on 2026-04-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nghiep_vu",
            "0003_phieuchi_hinh_thuc_thanh_toan_phieuchi_so_tien_vnd_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hoadon",
            name="da_thanh_toan",
            field=models.BooleanField(
                default=False,
                help_text="Đánh dấu khi phiếu thu đã được tạo tự động",
                verbose_name="Đã thanh toán",
            ),
        ),
        migrations.AddField(
            model_name="hoadon",
            name="da_xuat_kho",
            field=models.BooleanField(
                default=False,
                help_text="Đánh dấu khi phiếu xuất kho đã được tạo tự động",
                verbose_name="Đã xuất kho",
            ),
        ),
    ]
