# Generated by Django 5.0 on 2026-04-01 10:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danh_muc', '0004_alter_taikhoanketoan_loai_tai_khoan'),
        ('nghiep_vu', '0004_hoadon_da_thanh_toan_hoadon_da_xuat_kho'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttoan',
            name='ngay_dua_vao_su_dung',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày đưa vào sử dụng'),
        ),
        migrations.AddField(
            model_name='buttoanchitiet',
            name='so_chung_tu_goc',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Số chứng từ gốc'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='loai_hang_hoa',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Loại hàng hóa'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='ma_hang_hoa_gtgt',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mã hàng hóa GTGT'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='quy_so',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Quyển số'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='ky_hieu',
            field=models.CharField(blank=True, default='', help_text='Mẫu ký hiệu hóa đơn (VD: AA/26E)', max_length=10, verbose_name='Ký hiệu'),
        ),
        migrations.AlterField(
            model_name='hoadonchitiet',
            name='thue_suat',
            field=models.DecimalField(choices=[(Decimal('0'), '0% - Không chịu thuế'), (Decimal('5'), '5% - Nông, thủy sản,..'), (Decimal('8'), '8% - Giảm theo NĐ 70/2025'), (Decimal('10'), '10% - Thuế suất tiêu chuẩn')], decimal_places=0, default=Decimal('10'), max_digits=2, verbose_name='Thuế suất'),
        ),
        migrations.AlterField(
            model_name='phieuchi',
            name='tk_co',
            field=models.ForeignKey(help_text='Tài khoản ghi Có (111 hoặc 112)', on_delete=django.db.models.deletion.PROTECT, related_name='phieu_chi_co', to='danh_muc.taikhoanketoan', verbose_name='TK Có'),
        ),
        migrations.AlterField(
            model_name='phieuchi',
            name='tk_no',
            field=models.ForeignKey(help_text='Tài khoản ghi Nợ (331, 642, ...)', on_delete=django.db.models.deletion.PROTECT, related_name='phieu_chi_no', to='danh_muc.taikhoanketoan', verbose_name='TK Nợ'),
        ),
        migrations.AlterField(
            model_name='phieuthu',
            name='tk_co',
            field=models.ForeignKey(help_text='Tài khoản ghi Có (131, 511, ...)', on_delete=django.db.models.deletion.PROTECT, related_name='phieu_thu_co', to='danh_muc.taikhoanketoan', verbose_name='TK Có'),
        ),
        migrations.AlterField(
            model_name='phieuthu',
            name='tk_no',
            field=models.ForeignKey(help_text='Tài khoản ghi Nợ (111 hoặc 112)', on_delete=django.db.models.deletion.PROTECT, related_name='phieu_thu_no', to='danh_muc.taikhoanketoan', verbose_name='TK Nợ'),
        ),
    ]
