# Generated by Django 6.0.3 on 2026-04-03 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nghiep_vu", "0006_add_tt99_vouchers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bangphanbonvlccdcchitiet",
            options={},
        ),
        migrations.AlterModelOptions(
            name="bangthanhtoantienluongchitiet",
            options={},
        ),
        migrations.RemoveField(
            model_name="bangthanhtoantienluongchitiet",
            name="nhan_vien",
        ),
        migrations.AddField(
            model_name="bangphanbonvlccdc",
            name="but_toan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bang_phan_bo_nvl_ccdc_set",
                to="nghiep_vu.buttoan",
                verbose_name="Bút toán",
            ),
        ),
        migrations.AddField(
            model_name="bangthanhtoantienluong",
            name="but_toan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bang_thanh_toan_tien_luong_set",
                to="nghiep_vu.buttoan",
                verbose_name="Bút toán",
            ),
        ),
        migrations.AddField(
            model_name="bienbangiaonhantscd",
            name="but_toan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bien_ban_giao_nhan_tscd_set",
                to="nghiep_vu.buttoan",
                verbose_name="Bút toán",
            ),
        ),
        migrations.AddField(
            model_name="bienbanthanhlytscd",
            name="but_toan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bien_ban_thanh_ly_tscd_set",
                to="nghiep_vu.buttoan",
                verbose_name="Bút toán",
            ),
        ),
        migrations.AddField(
            model_name="giaydenghitamung",
            name="but_toan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="giay_de_nghi_tam_ung_set",
                to="nghiep_vu.buttoan",
                verbose_name="Bút toán",
            ),
        ),
        migrations.AddField(
            model_name="giaythanhtoantamung",
            name="but_toan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="giay_thanh_toan_tam_ung_set",
                to="nghiep_vu.buttoan",
                verbose_name="Bút toán",
            ),
        ),
    ]
