# Generated by Django 6.0.3 on 2026-04-02 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('danh_muc', '0004_alter_taikhoanketoan_loai_tai_khoan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeXuatMuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_de_xuat', models.CharField(max_length=50, unique=True, verbose_name='Số đề xuất')),
                ('ngay', models.DateField(verbose_name='Ngày')),
                ('nguoi_de_xuat', models.CharField(max_length=150, verbose_name='Người đề xuất')),
                ('ly_do', models.TextField(verbose_name='Lý do')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối'), ('da_mua', 'Đã mua')], default='draft', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Đề xuất mua hàng',
                'verbose_name_plural': 'Đề xuất mua hàng',
                'ordering': ['-ngay'],
            },
        ),
        migrations.CreateModel(
            name='BangPhanBoChiPhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chung_tu_goc_object_id', models.PositiveIntegerField(verbose_name='ID chứng từ gốc')),
                ('loai_chi_phi', models.CharField(choices=[('van_chuyen', 'Vận chuyển'), ('thue_quan', 'Thuế quan'), ('bao_hiem', 'Bảo hiểm'), ('khac', 'Khác')], max_length=20, verbose_name='Loại chi phí')),
                ('tong_chi_phi', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Tổng chi phí')),
                ('doi_tuong_phan_bo', models.CharField(help_text='Theo giá trị hoặc số lượng', max_length=50, verbose_name='Đối tượng phân bổ')),
                ('so_tien_phan_bo', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Số tiền phân bổ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('chung_tu_goc_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Loại chứng từ gốc')),
            ],
            options={
                'verbose_name': 'Bảng phân bổ chi phí',
                'verbose_name_plural': 'Bảng phân bổ chi phí',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonDatHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_don_hang', models.CharField(max_length=50, unique=True, verbose_name='Số đơn hàng')),
                ('ngay', models.DateField(verbose_name='Ngày')),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tổng tiền')),
                ('ngay_giao_du_kien', models.DateField(blank=True, null=True, verbose_name='Ngày giao dự kiến')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã xác nhận'), ('received', 'Đã nhận hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=12, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Người tạo')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Người cập nhật')),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='don_dat_hang', to='danh_muc.nhacungcap', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Đơn đặt hàng',
                'verbose_name_plural': 'Đơn đặt hàng',
                'ordering': ['-ngay'],
            },
        ),
        migrations.CreateModel(
            name='DonDatHangChiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số lượng')),
                ('so_luong_da_nhan', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số lượng đã nhận')),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Đơn giá')),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Thành tiền')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='mua_hang.dondathang', verbose_name='Đơn hàng')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.hanghoa', verbose_name='Hàng hóa')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn đặt hàng',
                'verbose_name_plural': 'Chi tiết đơn đặt hàng',
            },
        ),
        migrations.CreateModel(
            name='TraHangNCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_chung_tu', models.CharField(max_length=50, unique=True, verbose_name='Số chứng từ')),
                ('ngay', models.DateField(verbose_name='Ngày')),
                ('ly_do_tra', models.TextField(verbose_name='Lý do trả')),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Tổng tiền')),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='draft', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tra_hang', to='danh_muc.nhacungcap', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Trả hàng NCC',
                'verbose_name_plural': 'Trả hàng NCC',
                'ordering': ['-ngay'],
            },
        ),
    ]
