# Generated by Django 6.0.3 on 2026-04-03 03:31

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore[var-annotated]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=150, verbose_name="Người dùng")),
                ("action", models.CharField(max_length=50, verbose_name="Hành động")),
                (
                    "url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="URL"
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, default="", max_length=45, verbose_name="Địa chỉ IP"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Thời gian"),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Tên model"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="ID đối tượng",
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(blank=True, null=True, verbose_name="Giá trị cũ"),
                ),
                (
                    "new_value",
                    models.JSONField(blank=True, null=True, verbose_name="Giá trị mới"),
                ),
            ],
            options={
                "verbose_name": "Nhật ký kiểm tra",
                "verbose_name_plural": "Nhật ký kiểm tra",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CauHinhHeThong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tien_te_mac_dinh",
                    models.CharField(
                        default="VND", max_length=10, verbose_name="Tiền tệ mặc định"
                    ),
                ),
                (
                    "ty_gia",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=20,
                        verbose_name="Tỷ giá",
                    ),
                ),
                (
                    "thue_tndn_15",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        max_digits=5,
                        verbose_name="Thuế TNDN 15%",
                    ),
                ),
                (
                    "thue_tndn_20",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=5,
                        verbose_name="Thuế TNDN 20%",
                    ),
                ),
                (
                    "thue_vat_0",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Thuế VAT 0%",
                    ),
                ),
                (
                    "thue_vat_5",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        max_digits=5,
                        verbose_name="Thuế VAT 5%",
                    ),
                ),
                (
                    "thue_vat_8",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8.00"),
                        max_digits=5,
                        verbose_name="Thuế VAT 8%",
                    ),
                ),
                (
                    "thue_vat_10",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        max_digits=5,
                        verbose_name="Thuế VAT 10%",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Cấu hình hệ thống",
                "verbose_name_plural": "Cấu hình hệ thống",
            },
        ),
        migrations.CreateModel(
            name="KyKeToan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nam", models.IntegerField(verbose_name="Năm")),
                ("ngay_bat_dau", models.DateField(verbose_name="Ngày bắt đầu")),
                ("ngay_ket_thuc", models.DateField(verbose_name="Ngày kết thúc")),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("open", "Mở"),
                            ("locked", "Khóa"),
                            ("closed", "Đóng"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Kỳ kế toán",
                "verbose_name_plural": "Kỳ kế toán",
                "ordering": ["-nam", "ngay_bat_dau"],
            },
        ),
        migrations.CreateModel(
            name="ThongTinCongTy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ten_cong_ty",
                    models.CharField(max_length=255, verbose_name="Tên công ty"),
                ),
                (
                    "ma_so_thue",
                    models.CharField(max_length=20, verbose_name="Mã số thuế"),
                ),
                (
                    "dia_chi",
                    models.TextField(blank=True, default="", verbose_name="Địa chỉ"),
                ),
                (
                    "dien_thoai",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Điện thoại"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "nguoi_dai_dien",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người đại diện",
                    ),
                ),
                (
                    "chuc_vu_ndd",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Chức vụ người đại diện",
                    ),
                ),
                (
                    "ke_toan_truong",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Kế toán trưởng",
                    ),
                ),
                (
                    "hinh_thuc_ke_toan",
                    models.CharField(
                        choices=[
                            ("nhat_ky_chung", "Nhật ký chung"),
                            ("nhat_ky_so_cai", "Nhật ký - Sổ cái"),
                            ("chung_tu_ghi_so", "Chứng từ ghi sổ"),
                            ("nhat_ky_chung_tu", "Nhật ký chứng từ"),
                        ],
                        default="nhat_ky_chung",
                        max_length=30,
                        verbose_name="Hình thức kế toán",
                    ),
                ),
                (
                    "phuong_phap_gtgt",
                    models.CharField(
                        choices=[("khau_tru", "Khấu trừ"), ("truc_tiep", "Trực tiếp")],
                        default="khau_tru",
                        max_length=20,
                        verbose_name="Phương pháp GTGT",
                    ),
                ),
                (
                    "phuong_phap_ton_kho",
                    models.CharField(
                        choices=[
                            ("nhap_truoc_xuat_truoc", "Nhập trước xuất trước (FIFO)"),
                            ("nhap_sau_xuat_truoc", "Nhập sau xuất trước (LIFO)"),
                            ("binh_quan_lien_hoan", "Bình quân liên hoàn"),
                            ("binh_quan_cuoi_ky", "Bình quân cuối kỳ"),
                            ("thuc_te_lich_trinh", "Thực tế đích danh"),
                        ],
                        default="binh_quan_lien_hoan",
                        max_length=30,
                        verbose_name="Phương pháp tồn kho",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos/", verbose_name="Logo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Thông tin công ty",
                "verbose_name_plural": "Thông tin công ty",
            },
        ),
    ]
