# Generated by Django 6.0.3 on 2026-04-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("he_thong", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaiTro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Mã vai trò"
                    ),
                ),
                ("ten", models.CharField(max_length=100, verbose_name="Tên vai trò")),
                (
                    "mo_ta",
                    models.TextField(blank=True, default="", verbose_name="Mô tả"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Vai trò",
                "verbose_name_plural": "Vai trò",
                "ordering": ["ma"],
            },
        ),
    ]
