# Generated by Django 6.0.3 on 2026-04-03 04:24

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("danh_muc", "0007_fix_coa_tt99_compliance"),
        ("he_thong", "0002_vaitro"),
        ("kho", "0002_khoentry_is_opening"),
        ("tai_san", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoDuDauKy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doi_tuong_ma",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mã khách hàng/nhà cung cấp (cho TK 131, 331)",
                        max_length=20,
                        verbose_name="Mã đối tượng",
                    ),
                ),
                (
                    "so_du_no",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Số dư Nợ",
                    ),
                ),
                (
                    "so_du_co",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=20,
                        verbose_name="Số dư Có",
                    ),
                ),
                ("nam", models.IntegerField(verbose_name="Năm")),
                (
                    "da_khoa",
                    models.BooleanField(
                        default=False,
                        help_text="Không cho phép chỉnh sửa khi đã khóa",
                        verbose_name="Đã khóa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
                (
                    "hang_hoa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="so_du_dau_ky",
                        to="kho.vattuhanghoa",
                        verbose_name="Hàng hóa",
                    ),
                ),
                (
                    "kho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="so_du_dau_ky",
                        to="kho.kho",
                        verbose_name="Kho",
                    ),
                ),
                (
                    "tai_khoan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="so_du_dau_ky",
                        to="danh_muc.taikhoanketoan",
                        verbose_name="Tài khoản",
                    ),
                ),
                (
                    "tai_san",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="so_du_dau_ky",
                        to="tai_san.taisancodinh",
                        verbose_name="Tài sản cố định",
                    ),
                ),
            ],
            options={
                "verbose_name": "Số dư đầu kỳ",
                "verbose_name_plural": "Số dư đầu kỳ",
                "ordering": ["tai_khoan__ma_tai_khoan", "doi_tuong_ma"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tai_khoan", "doi_tuong_ma", "nam"),
                        name="unique_so_du_tai_khoan_doi_tuong_nam",
                    )
                ],
            },
        ),
    ]
