# Generated by Django 6.0.3 on 2026-04-06 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("he_thong", "0003_sodudauky"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_khach_hang",
                    models.CharField(
                        help_text="Tự động sinh (KH001, KH002, ...)",
                        max_length=20,
                        unique=True,
                        verbose_name="Mã khách hàng",
                    ),
                ),
                (
                    "ten_cong_ty",
                    models.CharField(max_length=255, verbose_name="Tên công ty"),
                ),
                (
                    "ma_so_thue",
                    models.CharField(max_length=20, verbose_name="Mã số thuế"),
                ),
                (
                    "nganh_nghe",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Ngành nghề",
                    ),
                ),
                (
                    "db_path",
                    models.CharField(
                        help_text="VD: data/clients/client_001_2026.sqlite3",
                        max_length=500,
                        verbose_name="Đường dẫn CSDL",
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("active", "Hoạt động"),
                            ("suspended", "Tạm khóa"),
                            ("expired", "Hết hạn"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Khách hàng (Dịch vụ kế toán)",
                "verbose_name_plural": "Khách hàng (Dịch vụ kế toán)",
                "ordering": ["ma_khach_hang"],
            },
        ),
        migrations.CreateModel(
            name="ClientUserMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_mappings",
                        to="he_thong.client",
                        verbose_name="Khách hàng",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_mappings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
                (
                    "vai_tro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="he_thong.vaitro",
                        verbose_name="Vai trò (theo khách hàng)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phân quyền khách hàng",
                "verbose_name_plural": "Phân quyền khách hàng",
                "ordering": ["client__ma_khach_hang"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "user"), name="unique_client_user_mapping"
                    )
                ],
            },
        ),
    ]
