# Generated by Django 5.2.12 on 2026-04-01 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaiSanCoDinh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_tai_san",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Mã tài sản"
                    ),
                ),
                (
                    "ten_tai_san",
                    models.CharField(max_length=255, verbose_name="Tên tài sản"),
                ),
                (
                    "nhom_tai_san",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nhóm tài sản",
                    ),
                ),
                (
                    "so_luong",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=12,
                        verbose_name="Số lượng",
                    ),
                ),
                (
                    "nguyen_gia",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Giá trị ban đầu của tài sản",
                        max_digits=20,
                        verbose_name="Nguyên giá",
                    ),
                ),
                (
                    "gia_tri_con_lai",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Nguyên giá - Khấu hao lũy kế",
                        max_digits=20,
                        verbose_name="Giá trị còn lại",
                    ),
                ),
                (
                    "khau_hao_luy_ke",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Khấu hao lũy kế",
                    ),
                ),
                (
                    "thoi_gian_khau_hao_thang",
                    models.IntegerField(
                        help_text="Số tháng khấu hao theo quy định",
                        verbose_name="Thời gian khấu hao (tháng)",
                    ),
                ),
                (
                    "muc_khau_hao_thang",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tính tự động: Nguyên giá / Thời gian khấu hao",
                        max_digits=20,
                        verbose_name="Mức khấu hao tháng",
                    ),
                ),
                (
                    "phuong_phap_khau_hao",
                    models.CharField(
                        choices=[
                            ("duong_thang", "Đường thẳng (Straight-line)"),
                            ("giam_dan", "Giảm dần (Declining balance)"),
                        ],
                        default="duong_thang",
                        max_length=15,
                        verbose_name="Phương pháp khấu hao",
                    ),
                ),
                (
                    "ngay_dua_vao_su_dung",
                    models.DateField(verbose_name="Ngày đưa vào sử dụng"),
                ),
                (
                    "ngay_khau_hao_cuoi",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày khấu hao cuối"
                    ),
                ),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("dang_su_dung", "Đang sử dụng"),
                            ("dung_khau_hao", "Đã khấu hao hết"),
                            ("thanh_ly", "Đã thanh lý"),
                        ],
                        default="dang_su_dung",
                        max_length=15,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "dia_chi",
                    models.TextField(
                        blank=True, default="", verbose_name="Địa chỉ / Nơi sử dụng"
                    ),
                ),
                (
                    "dien_giai",
                    models.TextField(blank=True, default="", verbose_name="Diễn giải"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tài sản cố định",
                "verbose_name_plural": "Tài sản cố định",
                "ordering": ["ma_tai_san"],
            },
        ),
        migrations.CreateModel(
            name="BangKhauHao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thang", models.IntegerField(verbose_name="Tháng")),
                ("nam", models.IntegerField(verbose_name="Năm")),
                (
                    "so_tien_khau_hao",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Số tiền khấu hao"
                    ),
                ),
                (
                    "khau_hao_luy_ke_dau_thang",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="KH lũy kế đầu tháng",
                    ),
                ),
                (
                    "khau_hao_luy_ke_cuoi_thang",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        verbose_name="KH lũy kế cuối tháng",
                    ),
                ),
                (
                    "da_hach_toan",
                    models.BooleanField(
                        default=False,
                        help_text="Đã tạo bút toán khấu hao",
                        verbose_name="Đã hạch toán",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "tai_san",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bang_khau_hao",
                        to="tai_san.taisancodinh",
                        verbose_name="Tài sản",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bảng khấu hao",
                "verbose_name_plural": "Bảng khấu hao",
                "ordering": ["nam", "thang"],
                "unique_together": {("tai_san", "thang", "nam")},
            },
        ),
    ]
