# Generated by Django 5.2.12 on 2026-04-01 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("danh_muc", "0003_khachhang_nganhang_nhacungcap_hanghoa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_kho",
                    models.CharField(max_length=10, unique=True, verbose_name="Mã kho"),
                ),
                ("ten_kho", models.CharField(max_length=255, verbose_name="Tên kho")),
                (
                    "dia_chi",
                    models.TextField(blank=True, default="", verbose_name="Địa chỉ"),
                ),
                (
                    "nguoi_phu_trach",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Người phụ trách",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kho",
                "verbose_name_plural": "Kho",
                "ordering": ["ma_kho"],
            },
        ),
        migrations.CreateModel(
            name="VatTuHangHoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phuong_phap_tinh_gia",
                    models.CharField(
                        choices=[
                            ("FIFO", "Nhập trước xuất trước (FIFO)"),
                            ("BINH_QUAN", "Bình quân gia quyền liên hoàn"),
                            ("DICH_DANH", "Đích danh"),
                        ],
                        default="FIFO",
                        max_length=10,
                        verbose_name="Phương pháp tính giá",
                    ),
                ),
                (
                    "don_vi_tinh",
                    models.CharField(
                        default="cái", max_length=50, verbose_name="Đơn vị tính"
                    ),
                ),
                (
                    "ton_toi_thieu",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Tồn tối thiểu",
                    ),
                ),
                (
                    "ton_toi_da",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Tồn tối đa",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
                (
                    "hang_hoa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vat_tu",
                        to="danh_muc.hanghoa",
                        verbose_name="Hàng hóa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vật tư hàng hóa",
                "verbose_name_plural": "Vật tư hàng hóa",
                "ordering": ["hang_hoa__ma_hang_hoa"],
            },
        ),
        migrations.CreateModel(
            name="KhoLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_lot",
                    models.CharField(max_length=50, unique=True, verbose_name="Mã lô"),
                ),
                ("ngay_nhap", models.DateField(verbose_name="Ngày nhập")),
                (
                    "so_luong_nhap",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="Số lượng nhập"
                    ),
                ),
                (
                    "so_luong_ton",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="Số lượng tồn"
                    ),
                ),
                (
                    "don_gia_nhap",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="Đơn giá nhập"
                    ),
                ),
                (
                    "han_dung",
                    models.DateField(blank=True, null=True, verbose_name="Hạn dùng"),
                ),
                (
                    "phieu_nhap_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
                (
                    "phieu_nhap_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "hang_hoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="kho.vattuhanghoa",
                        verbose_name="Hàng hóa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lô hàng",
                "verbose_name_plural": "Lô hàng",
                "ordering": ["ngay_nhap", "ma_lot"],
            },
        ),
        migrations.CreateModel(
            name="KhoEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loai",
                    models.CharField(
                        choices=[("NHAP", "Nhập kho"), ("XUAT", "Xuất kho")],
                        max_length=4,
                        verbose_name="Loại",
                    ),
                ),
                ("ngay_chung_tu", models.DateField(verbose_name="Ngày chứng từ")),
                (
                    "so_chung_tu",
                    models.CharField(max_length=50, verbose_name="Số chứng từ"),
                ),
                (
                    "loai_chung_tu",
                    models.CharField(
                        choices=[
                            ("NK", "Phiếu nhập kho"),
                            ("XK", "Phiếu xuất kho"),
                            ("DC", "Phiếu điều chuyển kho"),
                            ("KK", "Biên bản kiểm kê"),
                        ],
                        max_length=2,
                        verbose_name="Loại chứng từ",
                    ),
                ),
                (
                    "so_luong",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="Số lượng"
                    ),
                ),
                (
                    "don_gia",
                    models.DecimalField(
                        decimal_places=4, max_digits=20, verbose_name="Đơn giá"
                    ),
                ),
                (
                    "thanh_tien",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Thành tiền"
                    ),
                ),
                (
                    "gia_von_tam_tinh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Giá vốn tạm tính",
                    ),
                ),
                (
                    "gia_von_chinh_thuc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Giá vốn chính thức",
                    ),
                ),
                (
                    "dien_giai",
                    models.TextField(blank=True, default="", verbose_name="Diễn giải"),
                ),
                (
                    "da_dong_bo",
                    models.BooleanField(default=False, verbose_name="Đã đồng bộ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Người tạo"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Người cập nhật",
                    ),
                ),
                (
                    "kho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kho_entries",
                        to="kho.kho",
                        verbose_name="Kho",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kho_entries",
                        to="kho.kholot",
                        verbose_name="Lô hàng",
                    ),
                ),
                (
                    "hang_hoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kho_entries",
                        to="kho.vattuhanghoa",
                        verbose_name="Hàng hóa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký kho",
                "verbose_name_plural": "Nhật ký kho",
                "ordering": ["ngay_chung_tu", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="TonKho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "so_luong_ton",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=20,
                        verbose_name="Số lượng tồn",
                    ),
                ),
                (
                    "gia_tri_ton",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Giá trị tồn",
                    ),
                ),
                (
                    "ngay_cap_nhat_cuoi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ngày cập nhật cuối"
                    ),
                ),
                (
                    "kho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ton_kho",
                        to="kho.kho",
                        verbose_name="Kho",
                    ),
                ),
                (
                    "hang_hoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ton_kho",
                        to="kho.vattuhanghoa",
                        verbose_name="Hàng hóa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tồn kho",
                "verbose_name_plural": "Tồn kho",
                "ordering": ["hang_hoa__hang_hoa__ma_hang_hoa"],
                "unique_together": {("hang_hoa", "kho")},
            },
        ),
    ]
