# Generated by Django 6.0.3 on 2026-04-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kho", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="khoentry",
            name="is_opening",
            field=models.BooleanField(
                default=False,
                help_text="Đánh dấu đây là số dư đầu kỳ",
                verbose_name="Số dư đầu kỳ",
            ),
        ),
    ]
